import { describe, expect, it } from "vitest";
import { createAutoChartPlan } from "../lib/auto-chart";
import { chartDomain } from "../lib/charting";
import { addSeriesUnique, createWorkspaceChart, createWorkspaceSeries, deserializeWorkspace, duplicateChart, moveItem, patchSeries, removeSeries, serializeWorkspace } from "../lib/chart-workspace";

const series = (chart: string, ticker: string, metric: string, frequency: "weekly" | "ttm" | "annual" = "annual", axis: "left" | "right" = "left") => createWorkspaceSeries(chart, ticker, metric, frequency, "#4DA3FF", axis);

describe("independent chart workspace state", () => {
  it("adds a second metric without replacing the first", () => { let chart = createWorkspaceChart("chart-1", "AAPL", [series("chart-1", "AAPL", "stockPrice", "weekly")]); chart = addSeriesUnique(chart, series("chart-1", "AAPL", "revenue")); expect(chart.series.map((item) => item.metric)).toEqual(["stockPrice", "revenue"]); });
  it("adds a third metric", () => { let chart = createWorkspaceChart("chart-1", "AAPL", []); for (const metric of ["revenue", "freeCashFlow", "operatingMargin"]) chart = addSeriesUnique(chart, series("chart-1", "AAPL", metric)); expect(chart.series).toHaveLength(3); });
  it("adds a second company to the same metric", () => { let chart = createWorkspaceChart("chart-1", "AAPL", [series("chart-1", "AAPL", "revenue")]); chart = addSeriesUnique(chart, series("chart-1", "MSFT", "revenue")); expect(new Set(chart.series.map((item) => item.ticker)).size).toBe(2); });
  it("supports several companies and metrics without a Cartesian-state collision", () => { const items = [series("chart-1", "AAPL", "revenue"), series("chart-1", "AAPL", "stockPrice", "weekly"), series("chart-1", "MSFT", "revenue"), series("chart-1", "MSFT", "operatingMargin")]; expect(createWorkspaceChart("chart-1", "AAPL", items).series).toHaveLength(4); });
  it("does not add an exact duplicate series", () => { const item = series("chart-1", "AAPL", "revenue"); expect(addSeriesUnique(createWorkspaceChart("chart-1", "AAPL", [item]), item).series).toHaveLength(1); });
  it("distinguishes the same metric by frequency, transformation and axis", () => { const chart = createWorkspaceChart("chart-1", "AAPL", [series("chart-1", "AAPL", "revenue"), createWorkspaceSeries("chart-1", "AAPL", "revenue", "ttm", "#36D399", "right", "indexed")]); expect(new Set(chart.series.map((item) => item.uid)).size).toBe(2); });
  it("adds a second and third independent chart", () => { const charts = [1, 2, 3].map((id) => createWorkspaceChart(`chart-${id}`, "AAPL", [series(`chart-${id}`, "AAPL", "revenue")])); expect(charts.map((chart) => chart.id)).toEqual(["chart-1", "chart-2", "chart-3"]); });
  it("modifies one chart without affecting the others", () => { const first = createWorkspaceChart("chart-1", "AAPL", [series("chart-1", "AAPL", "revenue")]); const second = createWorkspaceChart("chart-2", "MSFT", [series("chart-2", "MSFT", "stockPrice", "weekly")]); const changed = [patchSeries(first, first.series[0].uid, { color: "#FF647C" }), second]; expect(changed[1]).toEqual(second); });
  it("removes one series only", () => { const items = [series("chart-1", "AAPL", "revenue"), series("chart-1", "AAPL", "freeCashFlow")]; const chart = createWorkspaceChart("chart-1", "AAPL", items); expect(removeSeries(chart, items[0].uid).series.map((item) => item.metric)).toEqual(["freeCashFlow"]); });
  it("removes one chart only", () => { const charts = [createWorkspaceChart("chart-1", "", []), createWorkspaceChart("chart-2", "", [])]; expect(charts.filter((chart) => chart.id !== "chart-1").map((chart) => chart.id)).toEqual(["chart-2"]); });
  it("duplicates a chart with new series identities", () => { const chart = createWorkspaceChart("chart-1", "AAPL", [series("chart-1", "AAPL", "revenue")]); const copy = duplicateChart(chart, "chart-2"); expect(copy.series[0].uid).toContain("chart-2"); expect(copy.series[0].uid).not.toBe(chart.series[0].uid); });
  it("reorders series without losing them", () => { const items = [series("chart-1", "AAPL", "revenue"), series("chart-1", "AAPL", "freeCashFlow")]; expect(moveItem(items, 1, -1).map((item) => item.metric)).toEqual(["freeCashFlow", "revenue"]); });
  it("reorders charts independently", () => { const charts = [createWorkspaceChart("chart-1", "", []), createWorkspaceChart("chart-2", "", [])]; expect(moveItem(charts, 0, 1).map((chart) => chart.id)).toEqual(["chart-2", "chart-1"]); });
  it("supports Stock Price with several fundamentals", () => { const chart = createWorkspaceChart("chart-1", "AAPL", [series("chart-1", "AAPL", "stockPrice", "weekly"), series("chart-1", "AAPL", "revenue", "ttm"), series("chart-1", "AAPL", "freeCashFlow", "annual")]); expect(chart.series.map((item) => item.frequency)).toEqual(["weekly", "ttm", "annual"]); });
  it("supports two axes", () => { const chart = createWorkspaceChart("chart-1", "AAPL", [series("chart-1", "AAPL", "revenue"), series("chart-1", "AAPL", "operatingMargin", "annual", "right")]); expect(new Set(chart.series.map((item) => item.axis))).toEqual(new Set(["left", "right"])); });
  it("splits more than two unit families into panels", () => { const plan = createAutoChartPlan([{ id: "a", ticker: "AAPL", metric: "revenue" }, { id: "b", ticker: "AAPL", metric: "operatingMargin" }, { id: "c", ticker: "AAPL", metric: "dilutedShares" }]); expect(new Set(plan.map((item) => item.panel)).size).toBe(3); });
  it("stores a valid custom axis range", () => { const chart = createWorkspaceChart("chart-1", "", []); chart.leftAxis = { ...chart.leftAxis, scale: "custom", minimum: -10, maximum: 30 }; expect(chartDomain([], "custom", { min: chart.leftAxis.minimum!, max: chart.leftAxis.maximum! }).domain).toEqual([-10, 30]); });
  it("supports Start at Zero", () => expect(chartDomain([5, 10], "zero").domain[0]).toBe(0));
  it("accepts logarithmic scale for positive values", () => expect(chartDomain([1, 10], "log").warning).toBeUndefined());
  it("refuses logarithmic scale for negative values", () => expect(chartDomain([-1, 10], "log").warning).toMatch(/positive/));
  it("changes style and color independently", () => { const chart = createWorkspaceChart("chart-1", "", [series("chart-1", "AAPL", "revenue")]); const changed = patchSeries(chart, chart.series[0].uid, { chartType: "area", stroke: "dashed", color: "#A78BFA" }); expect(changed.series[0]).toMatchObject({ chartType: "area", stroke: "dashed", color: "#A78BFA" }); });
  it("stores preset and custom periods", () => { const chart = { ...createWorkspaceChart("chart-1", "", []), range: "custom" as const, customStart: "2020-01-01", customEnd: "2025-12-31" }; expect(chart).toMatchObject({ range: "custom", customStart: "2020-01-01", customEnd: "2025-12-31" }); });
  it("stores AVG 5Y and rolling average on separate series", () => { const first = { ...series("chart-1", "AAPL", "revenue"), average: "5y" as const }; const second = { ...series("chart-1", "AAPL", "stockPrice", "weekly"), average: "rolling" as const, rollingWindow: 20 }; expect([first.average, second.average]).toEqual(["5y", "rolling"]); });
  it("stores several CAGR horizons in the legend", () => { const item = { ...series("chart-1", "AAPL", "revenue"), cagrHorizons: ["3", "5", "10", "max"] as const }; expect(item.cagrHorizons).toHaveLength(4); });
  it("saves and reloads layouts losslessly", () => { const charts = [createWorkspaceChart("chart-1", "AAPL", [series("chart-1", "AAPL", "revenue")])]; expect(deserializeWorkspace(serializeWorkspace(charts))).toEqual(charts); });
  it("rejects malformed saved layouts", () => expect(() => deserializeWorkspace('{"id":"chart-1"}')).toThrow(/Invalid/));
  it("preserves healthy series when a peer errors", () => { const chart = createWorkspaceChart("chart-1", "", [series("chart-1", "GOOD", "revenue"), series("chart-1", "FAIL", "stockPrice", "weekly")]); const errors = { [chart.series[1].uid]: "Market provider unavailable" }; expect(chart.series.filter((item) => !errors[item.uid]).map((item) => item.ticker)).toEqual(["GOOD"]); expect(chart.series).toHaveLength(2); });
});
