import { describe,expect,it } from "vitest";
import { calculateDcf,calculateWacc,dcfToCsv,defaultDcfAssumptions,sensitivityMatrix } from "../lib/dcf";

const base={revenue:1000,operatingMargin:.2,freeCashFlow:150,dilutedShares:100,cash:200,debt:100};
describe("professional DCF engine",()=>{
  it("calculates cost of equity, debt weights and WACC",()=>{const result=calculateWacc({riskFreeRate:.04,equityRiskPremium:.05,beta:1.2,preTaxCostOfDebt:.06,taxRate:.25,marketValueEquity:900,debtValue:100});expect(result.costOfEquity).toBeCloseTo(.1);expect(result.afterTaxCostOfDebt).toBeCloseTo(.045);expect(result.wacc).toBeCloseTo(.0945)});
  it("reconstructs NOPAT and FCFF",()=>{const assumptions=defaultDcfAssumptions(base,5);const result=calculateDcf(base,assumptions);const first=result.projections[0];expect(first.nopat).toBeCloseTo(first.operatingIncome*(1-first.taxRate));expect(first.freeCashFlow).toBeCloseTo(first.nopat+first.depreciation-first.capex-first.changeInWorkingCapital)});
  it("discounts forecast cash flows and terminal value into enterprise value",()=>{const result=calculateDcf(base,defaultDcfAssumptions(base,5));expect(result.presentValueForecast).toBeGreaterThan(0);expect(result.enterpriseValue).toBeCloseTo(result.presentValueForecast+result.presentValueTerminal!)});
  it("bridges net cash and net debt to equity value",()=>{const result=calculateDcf(base,defaultDcfAssumptions(base,5));expect(result.equityValue).toBeCloseTo(result.enterpriseValue!+100)});
  it("uses projected diluted shares for per-share value",()=>{const assumptions=defaultDcfAssumptions(base,5);assumptions.shareChange=Array(5).fill(.1);const result=calculateDcf(base,assumptions);expect(result.projections.at(-1)!.dilutedShares).toBeCloseTo(100*Math.pow(1.1,5));expect(result.intrinsicValuePerShare).toBeCloseTo(result.equityValue!/result.projections.at(-1)!.dilutedShares)});
  it("keeps bear, base and bull assumptions independent",()=>{const bear=calculateDcf(base,defaultDcfAssumptions(base,10,"bear"));const middle=calculateDcf(base,defaultDcfAssumptions(base,10,"base"));const bull=calculateDcf(base,defaultDcfAssumptions(base,10,"bull"));expect(bear.intrinsicValuePerShare!).toBeLessThan(middle.intrinsicValuePerShare!);expect(middle.intrinsicValuePerShare!).toBeLessThan(bull.intrinsicValuePerShare!)});
  it("fails closed when perpetual growth is at least WACC",()=>{const assumptions=defaultDcfAssumptions(base,5);assumptions.terminalGrowth=assumptions.wacc;const result=calculateDcf(base,assumptions);expect(result.terminalValue).toBeNull();expect(result.warnings.join(" ")).toMatch(/lower than WACC/)});
  it("fails closed rather than manufacturing a negative terminal value",()=>{const assumptions=defaultDcfAssumptions({...base,operatingMargin:-.2,freeCashFlow:-50},5);assumptions.operatingMargin=Array(5).fill(-.2);const result=calculateDcf(base,assumptions);expect(result.terminalValue).toBeNull();expect(result.warnings.join(" ")).toMatch(/not positive/)});
  it("fails closed for zero WACC and non-positive exit multiples",()=>{const perpetual=defaultDcfAssumptions(base,5);perpetual.wacc=0;expect(calculateDcf(base,perpetual).terminalValue).toBeNull();const exit={...defaultDcfAssumptions(base,5),terminalMethod:"exit-multiple" as const,exitMultiple:0};expect(calculateDcf(base,exit).terminalValue).toBeNull()});
  it("supports direct-FCF fallback as a distinct method",()=>{const assumptions=defaultDcfAssumptions(base,5);assumptions.method="direct-fcf";assumptions.directFcfMargin=Array(5).fill(.1);const result=calculateDcf(base,assumptions);expect(result.projections[0].freeCashFlow).toBeCloseTo(result.projections[0].revenue*.1)});
  it("creates perpetual-growth and exit-multiple sensitivity tables",()=>{const perpetual=defaultDcfAssumptions(base,5);expect(sensitivityMatrix(base,perpetual,[.08,.09],[.02,.025])).toHaveLength(2);const exit={...perpetual,terminalMethod:"exit-multiple" as const};expect(sensitivityMatrix(base,exit,[.08],[15,20])[0]).toHaveLength(2)});
  it("exports assumptions and results",()=>{const assumptions=defaultDcfAssumptions(base,5);expect(dcfToCsv(calculateDcf(base,assumptions),assumptions)).toMatch(/intrinsic_value_per_share/)});
});
