import { describe, expect, it } from "vitest";
import { alignMixedSeries, fundamentalObservations, indexObservationsTo100, marketObservations, updateSeriesDefinition, visibleRawObservations } from "../lib/mixed-series";
import { analyzeVisibleSeries } from "../lib/series-analysis";
import type { CompanyDataset, MarketBar, SeriesObservation } from "../lib/types";

const fact=(metric:string,value:number,periodEnd:string,periodicity:"annual"|"quarterly"|"ttm")=>({metric,value,currency:"USD",unit:metric.includes("Shares")?"shares":"currency",periodEnd,periodicity,fiscalYear:2025,provenance:{provider:"SEC",sourceUrl:"sec",retrievedAt:"2026-01-01",concept:metric,status:"reported"}} as never);
const dataset={company:{name:"Test",ticker:"T",cik:"1",exchange:"X",currency:"USD",sector:"",description:""},retrievedAt:"2026-01-01",warnings:[],periods:[
  {label:"FY",fiscalYear:2025,periodEnd:"2025-12-31",periodicity:"annual",filingDate:"2026-02-01",accession:"a",currency:"USD",facts:{revenue:fact("revenue",100,"2025-12-31","annual"),dilutedShares:fact("dilutedShares",10,"2025-12-31","annual")}},
  {label:"TTM",fiscalYear:2025,periodEnd:"2025-12-31",periodicity:"ttm",filingDate:"2026-02-01",accession:"b",currency:"USD",facts:{operatingCashFlow:fact("operatingCashFlow",30,"2025-12-31","ttm"),capitalExpenditures:fact("capitalExpenditures",-10,"2025-12-31","ttm"),dilutedShares:fact("dilutedShares",10,"2025-12-31","ttm")}},
]} as CompanyDataset;
const obs=(date:string,value:number,frequency:"weekly"|"ttm"="weekly"):SeriesObservation=>({date,value,frequency,currency:"USD",unit:"perShare",source:"test",status:"Verified",rawObservation:true});

describe("mixed-frequency series engine",()=>{
  it("uses adjusted close for stock-price observations",()=>{const bars=[{date:"2026-01-02",periodStart:"2025-12-27",open:9,high:11,low:8,close:10,adjustedClose:8,volume:1,currency:"USD",ticker:"T",frequency:"weekly",sourceUrl:"yahoo"}] as MarketBar[];expect(marketObservations(bars,"stockPrice","weekly")[0].value).toBe(8)});
  it("positions fundamentals at fiscal end or public filing date",()=>{expect(fundamentalObservations(dataset,"revenuePerShare","annual","fiscal-period")[0].date).toBe("2025-12-31");expect(fundamentalObservations(dataset,"revenuePerShare","annual","as-reported")[0].date).toBe("2026-02-01")});
  it("combines weekly price and TTM without manufacturing weekly fundamentals",()=>{const price=[obs("2026-02-06",20),obs("2026-02-13",21)];const ttm=[obs("2026-02-01",2,"ttm")];const rows=alignMixedSeries([{definition:{id:"price",ticker:"T",metric:"stockPrice",frequency:"weekly",missingData:"report-points"},observations:price},{definition:{id:"fcf",ticker:"T",metric:"freeCashFlowPerShare",frequency:"ttm",missingData:"report-points"},observations:ttm}]);expect(rows).toHaveLength(3);expect(rows.find((row)=>row.date==="2026-02-06")?.cells.fcf).toBeNull();expect(ttm).toHaveLength(1)});
  it("step mode carries only display cells and exposes age",()=>{const source=[obs("2026-02-01",2,"ttm")];const rows=alignMixedSeries([{definition:{id:"fcf",ticker:"T",metric:"freeCashFlowPerShare",frequency:"ttm",missingData:"step-until-next-report"},observations:source},{definition:{id:"price",ticker:"T",metric:"stockPrice",frequency:"weekly",missingData:"report-points"},observations:[obs("2026-02-08",20)]}]);expect(rows.at(-1)?.cells.fcf).toMatchObject({value:2,carried:true,ageDays:7});expect(source).toHaveLength(1);expect(visibleRawObservations(source,"2026-01-01","2026-03-01")).toHaveLength(1)});
  it("indexes each raw series from its own first valid observation",()=>{expect(indexObservationsTo100([obs("2026-01-01",5),obs("2026-02-01",10)]).map((item)=>item.value)).toEqual([100,200])});
  it("calculates each CAGR from that series's raw endpoints, never carried display cells",()=>{const weekly=[obs("2025-01-03",100),obs("2026-01-02",121)],ttm=[obs("2025-03-31",10,"ttm"),obs("2026-03-31",11,"ttm")];const rows=alignMixedSeries([{definition:{id:"price",ticker:"T",metric:"stockPrice",frequency:"weekly",missingData:"report-points"},observations:weekly},{definition:{id:"fcf",ticker:"T",metric:"freeCashFlowPerShare",frequency:"ttm",missingData:"step-until-next-report"},observations:ttm}]);expect(rows.filter((row)=>row.cells.fcf?.carried)).not.toHaveLength(0);expect(analyzeVisibleSeries(weekly,"cagr").value).toBeCloseTo(.21,2);expect(analyzeVisibleSeries(ttm,"cagr").value).toBeCloseTo(.1,3)});
  it("changes one series frequency without mutating any peer",()=>{const definitions=[{id:"price",ticker:"T",metric:"stockPrice",frequency:"weekly" as const,missingData:"report-points" as const},{id:"revenue",ticker:"T",metric:"revenue",frequency:"annual" as const,missingData:"report-points" as const}];const updated=updateSeriesDefinition(definitions,"price",{frequency:"monthly"});expect(updated[0].frequency).toBe("monthly");expect(updated[1]).toEqual(definitions[1]);expect(definitions[0].frequency).toBe("weekly")});
  it("aligns monthly price, quarterly margin and annual revenue only on real dates",()=>{const definitions=[{definition:{id:"price",ticker:"T",metric:"stockPrice",frequency:"monthly" as const,missingData:"report-points" as const},observations:[obs("2026-01-31",20),obs("2026-02-28",22)]},{definition:{id:"margin",ticker:"T",metric:"freeCashFlowMargin",frequency:"quarterly" as const,missingData:"report-points" as const},observations:[{...obs("2026-02-15",.2),frequency:"quarterly" as const}]},{definition:{id:"revenue",ticker:"T",metric:"revenue",frequency:"annual" as const,missingData:"report-points" as const},observations:[{...obs("2026-02-01",100),frequency:"annual" as const}]}];const rows=alignMixedSeries(definitions);expect(rows.map((row)=>row.date)).toEqual(["2026-01-31","2026-02-01","2026-02-15","2026-02-28"]);expect(rows.find((row)=>row.date==="2026-02-28")?.cells.margin).toBeNull()});
});
