"use client";

import { useState } from "react";
import { Loader2, Play } from "lucide-react";
import { DEFAULT_WATCHLIST } from "@/lib/company-registry";
import { buildCoverage, COVERAGE_METRICS, type CoverageCell } from "@/lib/coverage";
import { METRICS } from "@/lib/metrics";
import type { CompanyDataset } from "@/lib/types";
import { getJson } from "@/lib/fetch-json";

export function CoverageMatrix({initialData}:{initialData:CompanyDataset}){
  const [coverage,setCoverage]=useState<Record<string,Record<string,CoverageCell>>>({[initialData.company.ticker]:buildCoverage(initialData)});const [progress,setProgress]=useState(0);const [running,setRunning]=useState(false);
  async function validateAll(){setRunning(true);let done=0;for(const company of DEFAULT_WATCHLIST){if(coverage[company.ticker]){done++;setProgress(done);continue}const attemptedAt=new Date().toISOString();if(!company.cik){setCoverage((current)=>({...current,[company.ticker]:Object.fromEntries(COVERAGE_METRICS.map((metric)=>[metric,{status:"Unavailable",source:"—",latestPeriod:"—",reason:company.resolutionNote,attemptedAt}]))}));done++;setProgress(done);continue}try{const data=await getJson<CompanyDataset>(`/api/company/${encodeURIComponent(company.ticker)}`,{what:company.ticker});setCoverage((current)=>({...current,[company.ticker]:buildCoverage(data)}))}catch(error){setCoverage((current)=>({...current,[company.ticker]:Object.fromEntries(COVERAGE_METRICS.map((metric)=>[metric,{status:"Unavailable",source:"—",latestPeriod:"—",reason:error instanceof Error?error.message:"Validation failed",attemptedAt}]))}))}done++;setProgress(done)}setRunning(false)}
  return <><section className="view-title"><div><span className="panel-kicker">DATA COVERAGE</span><h2>22-company coverage matrix</h2><p>Every cell distinguishes reported, calculated, partial and unavailable data. No estimate fills a gap.</p></div><button className="button secondary" onClick={validateAll} disabled={running}>{running?<Loader2 className="spin" size={14}/>:<Play size={14}/>} {running?`${progress}/22 validated`:"Validate complete watchlist"}</button></section><section className="panel coverage-matrix"><div className="table-scroll"><table className="financial-table"><thead><tr><th>Company</th>{COVERAGE_METRICS.map((metric)=><th key={metric}>{METRICS[metric]?.short??metric}</th>)}</tr></thead><tbody>{DEFAULT_WATCHLIST.map((company)=><tr key={company.ticker}><th>{company.ticker}<small>{company.currency} · {company.exchange}</small></th>{COVERAGE_METRICS.map((metric)=>{const cell=coverage[company.ticker]?.[metric];const detail=cell?.reason?`${cell.reason}${cell.attemptedAt?` · attempted ${cell.attemptedAt.slice(0,10)}`:""}`:cell?.latestPeriod;return <td key={metric} className={!cell||cell.status==="Unavailable"?"missing-cell":""} title={cell?`${cell.source} · ${cell.latestPeriod} · ${detail??""}`:"Not validated in this session"}><span className={`coverage-status ${cell?.status.toLowerCase().replaceAll(" ","-")??"queued"}`}>{cell?.status??"Queued"}</span><small>{detail??company.resolutionNote??"Run validation"}</small></td>})}</tr>)}</tbody></table></div></section></>;
}
