"use client";

import { useState } from "react";
import { AlertTriangle, CheckCircle2, ExternalLink, RefreshCw, ShieldCheck } from "lucide-react";
import { auditMetric, COVERAGE_METRICS } from "@/lib/coverage";
import { cagrForPeriods } from "@/lib/finance";
import { METRICS } from "@/lib/metrics";
import { formatChartValue, unitFamily } from "@/lib/auto-chart";
import type { CompanyDataset, Periodicity } from "@/lib/types";

const AUDIT_METRICS=[...COVERAGE_METRICS,"grossMargin","operatingMargin","netMargin","operatingCashFlowPerShare","netIncomePerShare"];
const CAGR_METRICS=["revenue","netIncome","operatingCashFlow","freeCashFlow","revenuePerShare","netIncomePerShare","freeCashFlowPerShare","dilutedShares"];

export function DataQuality({dataset,onRefresh}:{dataset:CompanyDataset;onRefresh:(dataset:CompanyDataset)=>void}){
  const [periodicity,setPeriodicity]=useState<Periodicity>("annual"); const [refreshing,setRefreshing]=useState(false); const [message,setMessage]=useState("");
  const quality=dataset.quality; const audits=AUDIT_METRICS.map((metric)=>auditMetric(dataset,metric,periodicity)); const annual=dataset.periods.filter((period)=>period.periodicity==="annual").sort((a,b)=>a.periodEnd.localeCompare(b.periodEnd));
  async function refresh(){setRefreshing(true);setMessage("");try{const response=await fetch(`/api/company/${encodeURIComponent(dataset.company.ticker)}?refresh=${Date.now()}`,{cache:"no-store"});const payload=await response.json() as CompanyDataset&{error?:string};if(!response.ok)throw new Error(payload.error||"Refresh failed");onRefresh(payload);setMessage(`Revalidated ${new Date(payload.retrievedAt).toLocaleString()}.`)}catch(error){setMessage(error instanceof Error?error.message:"Refresh failed")}finally{setRefreshing(false)}}
  return <div className="data-quality-page"><section className="view-title"><div><span className="panel-kicker">CENTRAL VALIDATION ENGINE</span><h2>Data Quality</h2><p>Coverage, source conflicts, normalization decisions and unavailable calculations remain explicit and auditable.</p></div><button className="button secondary" onClick={refresh} disabled={refreshing}><RefreshCw size={14} className={refreshing?"spin":""}/> Re-fetch & recalculate</button></section>{message&&<div className="notice"><ShieldCheck size={16}/><div><b>Validation refresh</b><p>{message}</p></div></div>}
    <section className="metrics-grid">{(quality?.coverage??[]).map((item)=><article className="metric-card" key={item.periodicity}><div className="metric-top"><span>{item.periodicity.toUpperCase()} COVERAGE</span>{item.periodCount?<CheckCircle2 size={14}/>:<AlertTriangle size={14}/>}</div><strong>{item.periodCount}</strong><div className="metric-delta positive">{item.firstPeriod??"—"}<span>through {item.lastPeriod??"—"}</span></div></article>)}</section>
    <section className="panel table-panel"><div className="panel-head"><div><span className="panel-kicker">EXACT AVAILABILITY</span><h2>Metric audit</h2></div><div className="segmented">{(["annual","quarterly","ttm"] as const).map((item)=><button className={periodicity===item?"active":""} onClick={()=>setPeriodicity(item)} key={item}>{item.toUpperCase()}</button>)}</div></div><div className="table-scroll"><table className="financial-table"><thead><tr><th>Metric</th><th>Status</th><th>Coverage</th><th>First</th><th>Last</th><th>Exact reason</th></tr></thead><tbody>{audits.map((audit)=><tr key={audit.metric}><th>{METRICS[audit.metric]?.label??audit.metric}</th><td>{audit.status}</td><td>{audit.available}/{audit.total}</td><td>{audit.firstPeriod??"—"}</td><td>{audit.lastPeriod??"—"}</td><td>{audit.reason}</td></tr>)}</tbody></table></div></section>
    <section className="panel table-panel"><div className="panel-head"><div><span className="panel-kicker">15Y / 20Y / MAXIMUM AVAILABLE</span><h2>CAGR availability audit</h2></div></div><div className="table-scroll"><table className="financial-table"><thead><tr><th>Metric</th>{[15,20,"max"].map((horizon)=><th key={horizon}>{horizon==="max"?"Maximum available":`${horizon}Y exact`}</th>)}</tr></thead><tbody>{CAGR_METRICS.map((metric)=><tr key={metric}><th>{METRICS[metric]?.label??metric}</th>{([15,20,"max"] as const).map((horizon)=>{const result=cagrForPeriods(annual,metric,horizon);return <td key={horizon} title={result.reason}><b>{result.value==null?"N/M":`${(result.value*100).toFixed(2)}%`}</b><small>{result.reason??`${result.startDate} → ${result.endDate} · ${result.years.toFixed(2)}y`}</small></td>})}</tr>)}</tbody></table></div></section>
    <section className="panel table-panel"><div className="panel-head"><div><span className="panel-kicker">ANOMALIES & CORRECTIONS</span><h2>Validation log</h2></div><span className="verified">{quality?.issues.length??0} flagged observations</span></div><div className="table-scroll"><table className="financial-table"><thead><tr><th>Period / Metric</th><th>Status</th><th>Raw</th><th>Normalized</th><th>Cause & action</th><th>Source</th></tr></thead><tbody>{quality?.issues.length?quality.issues.map((issue)=><tr key={issue.id}><th>{issue.period}<small>{METRICS[issue.metric]?.label??issue.metric}</small></th><td>{issue.status}</td><td>{issue.rawValue==null?"—":formatChartValue(issue.rawValue,unitFamily(issue.metric),"USD",true)}</td><td>{issue.normalizedValue==null?"—":formatChartValue(issue.normalizedValue,unitFamily(issue.metric),"USD",true)}</td><td>{issue.cause}<small>{issue.action}</small></td><td>{issue.sourceUrl?<a href={issue.sourceUrl} target="_blank" rel="noreferrer">Filing <ExternalLink size={11}/></a>:"—"}</td></tr>):<tr><td colSpan={6}>No validation exception detected. Verified outliers would remain listed here rather than being deleted.</td></tr>}</tbody></table></div></section>
    <section className="panel table-panel"><div className="panel-head"><div><span className="panel-kicker">CORPORATE ACTIONS</span><h2>Stock-split normalization</h2></div></div><div className="table-scroll"><table className="financial-table"><thead><tr><th>Effective date</th><th>Ratio</th><th>Method</th></tr></thead><tbody>{quality?.stockSplits.length?quality.stockSplits.map((split)=><tr key={split.date}><td>{split.date}</td><td>{split.ratio}:1</td><td>Applied only to earlier share facts whose filing predates the split; later restatements are not adjusted twice.</td></tr>):<tr><td colSpan={3}>No registered split normalization.</td></tr>}</tbody></table></div></section>
  </div>;
}
