"use client";

import { useEffect, useMemo, useState } from "react";
import { Area, Bar, CartesianGrid, ComposedChart, Line, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Info, Loader2, Plus, X } from "lucide-react";
import { CHART_DEFAULTS, CHART_PALETTE, chartDomain, indexedTo100, rechartsCurve, robustValues, type AnomalyMode, type CurveStyle, type ScaleMode } from "@/lib/charting";
import { DEFAULT_WATCHLIST } from "@/lib/company-registry";
import { validatedDerivedValue } from "@/lib/data-quality";
import { cagrForPeriods, safeDivide } from "@/lib/finance";
import { METRICS } from "@/lib/metrics";
import type { CompanyDataset, FinancialPeriod, Periodicity } from "@/lib/types";

const COMPARISON_METRICS=["stockPrice","marketCapitalization","priceToSales","priceToEarnings","priceToFreeCashFlow","freeCashFlowYield","revenue","revenueGrowth","revenuePerShare","grossProfit","operatingIncome","netIncome","operatingCashFlow","freeCashFlow","freeCashFlowMargin","freeCashFlowPerShare","freeCashFlowPerShareGrowth","grossMargin","operatingMargin","netMargin","netIncomePerShare","dilutedShares","sharesOutstanding","shareCountChange","stockBasedCompensation","cashConversion","roic"];
const PRICE_METRICS=new Set(["stockPrice","marketCapitalization","priceToSales","priceToEarnings","priceToFreeCashFlow","freeCashFlowYield"]);

function selectedPeriods(dataset:CompanyDataset,periodicity:Periodicity,range:number){const all=dataset.periods.filter((period)=>period.periodicity===periodicity).sort((a,b)=>a.periodEnd.localeCompare(b.periodEnd));return range===999?all:all.slice(-range)}
function seriesValue(periods:FinancialPeriod[],index:number,metric:string,price:number|null=null,anomalyMode:AnomalyMode="validated"){
  const period=periods[index]; const value=(key:string)=>validatedDerivedValue(period,key,anomalyMode); const shares=value("dilutedShares")??value("sharesOutstanding"); const marketCap=price!=null&&shares!=null?price*shares:null;
  if(metric==="stockPrice")return price;if(metric==="marketCapitalization")return marketCap;if(metric==="priceToSales")return safeDivide(marketCap,value("revenue"));if(metric==="priceToEarnings")return safeDivide(marketCap,value("netIncome"));if(metric==="priceToFreeCashFlow")return safeDivide(marketCap,value("freeCashFlow"));if(metric==="freeCashFlowYield")return safeDivide(value("freeCashFlow"),marketCap);if(metric==="roic")return null;
  const base=metric==="revenueGrowth"?"revenue":metric==="freeCashFlowPerShareGrowth"?"freeCashFlowPerShare":metric==="shareCountChange"?"dilutedShares":metric;const current=value(base);
  if(metric.endsWith("Growth")||metric==="shareCountChange"){const prior=index?validatedDerivedValue(periods[index-1],base,anomalyMode):null;return current!=null&&prior?current/prior-1:null}return current;
}

export function MultiStockComparison({initialData}:{initialData:CompanyDataset}){
  const [datasets,setDatasets]=useState<Record<string,CompanyDataset>>({[initialData.company.ticker]:initialData}); const [selected,setSelected]=useState([initialData.company.ticker]); const [loading,setLoading]=useState("");
  const [marketValues,setMarketValues]=useState<Record<string,number|null>>({}); const [fxRates,setFxRates]=useState<Record<string,number|null>>({});
  const [metric,setMetric]=useState("freeCashFlowPerShare"); const [periodicity,setPeriodicity]=useState<Periodicity>("annual"); const [range,setRange]=useState(()=>typeof window==="undefined"?999:Number(localStorage.getItem("finscope.comparisonRange"))||999); const [mode,setMode]=useState<"raw"|"growth"|"indexed">("raw"); const [currencyMode,setCurrencyMode]=useState<"native"|"USD"|"indexed">("native"); const [alignment,setAlignment]=useState<"fiscal"|"calendar">("fiscal"); const [scale,setScale]=useState<ScaleMode>("zero"); const [chartType,setChartType]=useState<"line"|"bar"|"area">("line");
  const [curveStyle,setCurveStyle]=useState<CurveStyle>(()=>typeof window==="undefined"?CHART_DEFAULTS.curve:(localStorage.getItem("finscope.curveStyle") as CurveStyle)||CHART_DEFAULTS.curve); const [anomalyMode,setAnomalyMode]=useState<AnomalyMode>(()=>typeof window==="undefined"?CHART_DEFAULTS.anomalyMode:(localStorage.getItem("finscope.anomalyMode") as AnomalyMode)||CHART_DEFAULTS.anomalyMode); const [robustScale,setRobustScale]=useState(false);
  useEffect(()=>localStorage.setItem("finscope.comparisonRange",String(range)),[range]); useEffect(()=>localStorage.setItem("finscope.curveStyle",curveStyle),[curveStyle]); useEffect(()=>localStorage.setItem("finscope.anomalyMode",anomalyMode),[anomalyMode]);

  async function add(ticker:string){if(selected.includes(ticker))return;setLoading(ticker);try{const response=await fetch(`/api/company/${encodeURIComponent(ticker)}?refresh=${Date.now()}`,{cache:"no-store"});const payload=await response.json() as CompanyDataset&{error?:string};if(!response.ok)throw new Error(payload.error);setDatasets((current)=>({...current,[ticker]:payload}));setSelected((current)=>[...current,ticker])}finally{setLoading("")}}
  useEffect(()=>{if(!PRICE_METRICS.has(metric))return;for(const ticker of selected){const dataset=datasets[ticker];if(!dataset)continue;const dates=selectedPeriods(dataset,periodicity,range).map((period)=>period.periodEnd);if(!dates.length)continue;fetch(`/api/prices/${encodeURIComponent(ticker)}?dates=${dates.join(",")}`).then((response)=>response.ok?response.json():null).then((value)=>{const payload=value as {points?:Array<{requestedDate:string;point?:{close:number}}>}|null;if(payload?.points)setMarketValues((current)=>({...current,...Object.fromEntries(payload.points!.map((item)=>[`${ticker}:${item.requestedDate}`,item.point?.close??null]))}))})}},[selected,datasets,periodicity,range,metric]);
  useEffect(()=>{if(currencyMode!=="USD")return;for(const ticker of selected){const dataset=datasets[ticker];if(!dataset||dataset.company.currency==="USD")continue;for(const date of selectedPeriods(dataset,periodicity,range).map((period)=>period.periodEnd)){const key=`${dataset.company.currency}:${date}`;if(key in fxRates)continue;fetch(`/api/fx?from=${dataset.company.currency}&to=USD&date=${date}`).then((response)=>response.ok?response.json():null).then((value)=>{const payload=value as {rate?:number}|null;setFxRates((current)=>({...current,[key]:payload?.rate??null}))})}}},[selected,datasets,periodicity,range,currencyMode,fxRates]);

  const normalized=useMemo(()=>selected.map((ticker)=>{const dataset=datasets[ticker];if(!dataset)return null;const periods=selectedPeriods(dataset,periodicity,range);let values=periods.map((period,index)=>seriesValue(periods,index,metric,marketValues[`${ticker}:${period.periodEnd}`]??null,anomalyMode));if(currencyMode==="USD"&&dataset.company.currency!=="USD"&&(METRICS[metric]?.kind==="currency"||METRICS[metric]?.kind==="perShare"))values=values.map((value,index)=>{const rate=fxRates[`${dataset.company.currency}:${periods[index].periodEnd}`];return value!=null&&rate!=null?value*rate:null});if(mode==="growth")values=periods.map((_,index)=>index&&values[index]!=null&&values[index-1]?values[index]!/values[index-1]!-1:null);if(mode==="indexed"||currencyMode==="indexed")values=indexedTo100(values);return {ticker,dataset,periods,values}}).filter(Boolean) as Array<{ticker:string;dataset:CompanyDataset;periods:FinancialPeriod[];values:Array<number|null>}> ,[selected,datasets,periodicity,range,metric,mode,currencyMode,marketValues,fxRates,anomalyMode]);
  const labels=[...new Set(normalized.flatMap((series)=>series.periods.map((period)=>alignment==="fiscal"?`${period.fiscalYear}${period.fiscalQuarter??""}`:period.periodEnd.slice(0,7))))].sort(); const data=labels.map((label)=>{const row:Record<string,string|number|null>={label};for(const series of normalized){const index=series.periods.findIndex((period)=>(alignment==="fiscal"?`${period.fiscalYear}${period.fiscalQuarter??""}`:period.periodEnd.slice(0,7))===label);row[series.ticker]=index>=0?series.values[index]:null;row[`${series.ticker}Date`]=index>=0?series.periods[index].periodEnd:""}return row});
  const values=data.flatMap((row)=>selected.map((ticker)=>row[ticker] as number|null)); const domain=chartDomain(robustScale?robustValues(values):values,scale); const percent=mode==="growth"||metric.endsWith("Growth")||METRICS[metric]?.kind==="percent"; const fiscalMonths=[...new Set(normalized.map((item)=>item.periods.at(-1)?.periodEnd.slice(5,7)))]; const mixedCurrency=[...new Set(normalized.map((item)=>item.dataset.company.currency))].length>1;
  const qualityRows=normalized.map((item)=>{const annual=item.dataset.periods.filter((period)=>period.periodicity==="annual").sort((a,b)=>a.periodEnd.localeCompare(b.periodEnd));const vals=annual.map((period,index)=>seriesValue(annual,index,metric,marketValues[`${item.ticker}:${period.periodEnd}`]??null,anomalyMode)).filter((value):value is number=>value!=null);const avg=(count:number)=>{const recent=vals.slice(-count);return recent.length?recent.reduce((a,b)=>a+b,0)/recent.length:null};const cagr=(years:number)=>PRICE_METRICS.has(metric)?null:cagrForPeriods(annual,metric,years).value;return {ticker:item.ticker,current:vals.at(-1)??null,avg5:avg(5),avg10:avg(10),cagr3:cagr(3),cagr5:cagr(5),cagr10:cagr(10),cagr20:cagr(20),available:vals.length}}).sort((a,b)=>(b.current??-Infinity)-(a.current??-Infinity));

  return <div className="comparison-page"><section className="view-title"><div><span className="panel-kicker">MULTI-STOCK ANALYSIS</span><h2>Multi-Stock Comparison</h2><p>Compare quality metrics without hiding currency, fiscal-calendar or availability differences.</p></div></section>
    <section className="panel comparison-controls"><div className="company-chips">{selected.map((ticker,index)=><span key={ticker}><i style={{background:CHART_PALETTE[index%10].value}}/>{ticker}<button onClick={()=>setSelected((current)=>current.filter((item)=>item!==ticker))}><X size={11}/></button></span>)}<label><Plus size={12}/><select defaultValue="" onChange={(event)=>{add(event.target.value);event.currentTarget.value=""}}><option value="" disabled>Add company…</option>{DEFAULT_WATCHLIST.filter((company)=>!selected.includes(company.ticker)&&company.resolutionStatus!=="unresolved").map((company)=><option value={company.ticker} key={company.ticker}>{company.ticker} · {company.name}</option>)}</select>{loading&&<Loader2 className="spin" size={12}/>}</label></div>
      <div className="comparison-options"><label>Metric<select value={metric} onChange={(event)=>setMetric(event.target.value)}>{COMPARISON_METRICS.map((key)=><option value={key} key={key}>{METRICS[key]?.label??key}</option>)}</select></label><label>Periods<select value={periodicity} onChange={(event)=>setPeriodicity(event.target.value as Periodicity)}><option value="annual">Annual</option><option value="quarterly">Quarterly</option><option value="ttm">TTM</option></select></label><label>History<select value={range} onChange={(event)=>setRange(Number(event.target.value))}><option value="5">5</option><option value="10">10</option><option value="20">20</option><option value="999">Max</option></select></label><label>Mode<select value={mode} onChange={(event)=>setMode(event.target.value as typeof mode)}><option value="raw">Raw</option><option value="growth">Growth</option><option value="indexed">Indexed to 100</option></select></label><label>Currency<select value={currencyMode} onChange={(event)=>setCurrencyMode(event.target.value as typeof currencyMode)}><option value="native">Native currency</option><option value="USD">Common USD</option><option value="indexed">Indexed comparison</option></select></label><label>Alignment<select value={alignment} onChange={(event)=>setAlignment(event.target.value as typeof alignment)}><option value="fiscal">Fiscal period</option><option value="calendar">Calendar period</option></select></label><label>Scale<select value={scale} onChange={(event)=>setScale(event.target.value as ScaleMode)}><option value="zero">Start at zero</option><option value="auto">Auto scale</option><option value="log">Logarithmic</option></select></label><label>Style<select value={chartType} onChange={(event)=>setChartType(event.target.value as typeof chartType)}><option value="line">Line</option><option value="bar">Bar</option><option value="area">Area</option></select></label><label>Curve<select value={curveStyle} onChange={(event)=>setCurveStyle(event.target.value as CurveStyle)}><option value="straight">Straight</option><option value="curved">Curved</option><option value="step">Step</option></select></label><label>Data<select value={anomalyMode} onChange={(event)=>setAnomalyMode(event.target.value as AnomalyMode)}><option value="validated">Validated</option><option value="raw">Raw</option></select></label><label><input type="checkbox" checked={robustScale} onChange={(event)=>setRobustScale(event.target.checked)}/> Robust scale</label></div></section>
    {mixedCurrency&&currencyMode==="native"&&<div className="notice"><Info size={16}/><div><b>Native currencies differ</b><p>Values retain their original currencies. Use indexed comparison or a verified historical FX conversion.</p></div></div>}{mixedCurrency&&currencyMode==="USD"&&<div className="notice"><Info size={16}/><div><b>Historical FX conversion</b><p>Each available observation uses its matching Yahoo FX session. Missing rates remain unavailable; a current rate is never substituted.</p></div></div>}{fiscalMonths.length>1&&alignment==="fiscal"&&<div className="notice"><Info size={16}/><div><b>Fiscal year-ends differ</b><p>Fiscal labels are aligned, but tooltips preserve actual dates. No calendar equivalence is implied.</p></div></div>}
    <section className="panel comparison-chart"><div className="panel-head"><div><span className="panel-kicker">{mode.toUpperCase()}</span><h2>{METRICS[metric]?.label}</h2></div><span className="verified">{selected.length} companies</span></div><div className="advanced-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data}><CartesianGrid stroke="var(--grid)" vertical={false}/><XAxis dataKey="label" tick={{fill:"var(--muted)",fontSize:10}}/><YAxis domain={domain.domain} scale={scale==="log"?"log":"linear"} tickFormatter={(value)=>mode==="indexed"||currencyMode==="indexed"?String(Math.round(value)):percent?`${(value*100).toFixed(0)}%`:new Intl.NumberFormat("en-US",{notation:"compact"}).format(value)}/>{scale!=="log"&&<ReferenceLine y={0} stroke="var(--border-strong)"/>}<Tooltip formatter={(value,name,item)=>[percent?`${(Number(value)*100).toFixed(1)}%`:Number(value).toLocaleString(),`${name} · ${item.payload[`${name}Date`]}`]}/>{selected.map((ticker,index)=>chartType==="bar"?<Bar key={ticker} dataKey={ticker} fill={CHART_PALETTE[index%10].value}/>:chartType==="area"?<Area key={ticker} type={rechartsCurve(curveStyle)} dataKey={ticker} stroke={CHART_PALETTE[index%10].value} fill={CHART_PALETTE[index%10].value} fillOpacity={.08} connectNulls={false}/>:<Line key={ticker} type={rechartsCurve(curveStyle)} dataKey={ticker} stroke={CHART_PALETTE[index%10].value} strokeWidth={2} dot={false} connectNulls={false}/>)}</ComposedChart></ResponsiveContainer></div><div className="panel-foot"><span>Axis: {scale} after {mode} transformation · {range===999?"Max history":`${range} periods`}</span><span>{robustScale?"Robust axis; observations unchanged":"Full-value axis"} · {anomalyMode}</span></div></section>
    <section className="panel quality-comparison"><div className="panel-head"><div><span className="panel-kicker">QUALITY COMPARISON</span><h2>Transparent ranking · {METRICS[metric]?.label}</h2></div></div><div className="table-scroll"><table className="financial-table"><thead><tr><th>Rank / Company</th><th>Current</th><th>5Y average</th><th>10Y average</th><th>3Y CAGR</th><th>5Y CAGR</th><th>10Y CAGR</th><th>20Y CAGR</th><th>Availability</th></tr></thead><tbody>{qualityRows.map((row,index)=><tr key={row.ticker}><th>#{index+1} · {row.ticker}</th>{[row.current,row.avg5,row.avg10].map((value,i)=><td key={i}>{value==null?"N/M":percent?`${(value*100).toFixed(1)}%`:value.toLocaleString(undefined,{notation:"compact",maximumFractionDigits:2})}</td>)}{[row.cagr3,row.cagr5,row.cagr10,row.cagr20].map((value,i)=><td key={i}>{value==null?"N/M":`${(value*100).toFixed(1)}%`}</td>)}<td>{row.available} annual facts</td></tr>)}</tbody></table></div></section>
  </div>;
}
