"use client";
import { useEffect,useMemo,useState } from "react";
import { Area,CartesianGrid,ComposedChart,Line,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { Info,Loader2 } from "lucide-react";
import { buildValuationHistory,VALUATION_DEFINITIONS,valuationAssessment,valuationSnapshot,valuationStatistics,type ValuationMetric } from "@/lib/valuation-history";
import type { CompanyDataset,PricePoint } from "@/lib/types";

const money=(value:number|null,currency:string)=>value==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency,notation:"compact",maximumFractionDigits:2}).format(value);
const display=(value:number|null,isYield:boolean)=>value==null?"N/M":isYield?`${(value*100).toFixed(2)}%`:`${value.toFixed(2)}×`;
export function ValuationAnalysis({dataset}:{dataset:CompanyDataset}){
  const ttm=useMemo(()=>dataset.periods.filter((period)=>period.periodicity==="ttm").sort((a,b)=>a.filingDate.localeCompare(b.filingDate)),[dataset]);const latest=ttm.at(-1)??dataset.periods.filter((period)=>period.periodicity==="annual").sort((a,b)=>a.periodEnd.localeCompare(b.periodEnd)).at(-1)!;
  const [points,setPoints]=useState<Record<string,PricePoint|null>>({});const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [metric,setMetric]=useState<ValuationMetric>("priceToFreeCashFlow");const [horizon,setHorizon]=useState(5);const [threshold,setThreshold]=useState(.1);const today=new Date().toISOString().slice(0,10);
  const dates=useMemo(()=>[...new Set([...ttm.map((period)=>period.filingDate),today])],[ttm,today]);
  useEffect(()=>{let active=true;queueMicrotask(()=>{setLoading(true);setError("")});fetch(`/api/prices/${dataset.company.ticker}?dates=${dates.join(",")}&published=1`).then(async(response)=>{const payload=await response.json() as {points?:Array<{requestedDate:string;point?:PricePoint;error?:string}>;error?:string};if(!response.ok)throw new Error(payload.error);if(active)setPoints(Object.fromEntries((payload.points??[]).map((item)=>[item.requestedDate,item.point??null])))}).catch((cause)=>active&&setError(cause instanceof Error?cause.message:"Market history unavailable")).finally(()=>active&&setLoading(false));return()=>{active=false}},[dataset.company.ticker,dates]);
  const history=useMemo(()=>buildValuationHistory(ttm,points),[ttm,points]);const current=points[today]?valuationSnapshot(latest,points[today]!):null;const stats=valuationStatistics(history,metric,current?.metrics[metric]??null,horizon);const definition=VALUATION_DEFINITIONS[metric];const chartData=history.map((item)=>({date:item.date,value:item.metrics[metric]})).filter((item)=>item.value!=null);const fiveYearStats=Object.fromEntries((Object.keys(VALUATION_DEFINITIONS) as ValuationMetric[]).map((key)=>[key,valuationStatistics(history,key,current?.metrics[key]??null,5)]));
  return <div className="valuation-page"><section className="view-title"><div><span className="panel-kicker">CURRENT VS HISTORICAL VALUATION</span><h2>Valuation without look-ahead bias</h2><p>Each historical price is paired only with TTM fundamentals available on or before that trading session.</p></div></section>{loading&&<div className="notice"><Loader2 className="spin" size={17}/><div><b>Building valuation history</b><p>Matching TTM filing dates to real trading sessions.</p></div></div>}{error&&<div className="notice"><Info size={17}/><div><b>Market history unavailable</b><p>{error}</p></div></div>}
    {current&&<div className="price-proof"><div><span>Current price</span><strong>{money(current.price,dataset.company.currency)}</strong></div><div><span>Price date</span><strong>{current.date}</strong></div><div><span>Fundamental period</span><strong>TTM {current.periodEnd}</strong></div><div><span>Filed / available</span><strong>{current.filingDate}</strong></div><div><span>Market cap</span><strong>{money(current.marketCap,dataset.company.currency)}</strong></div><div><span>Enterprise value</span><strong>{money(current.enterpriseValue,dataset.company.currency)}</strong></div></div>}
    <section className="valuation-grid">{(Object.keys(VALUATION_DEFINITIONS) as ValuationMetric[]).map((key)=>{const item=VALUATION_DEFINITIONS[key],value=current?.metrics[key]??null,s=fiveYearStats[key];return <article className="valuation-card" key={key}><span>{item.label}</span><strong>{display(value,item.yield)}</strong><small>{valuationAssessment(s,item.yield,threshold)} · {s.observations} obs.</small><div className="valuation-statline"><span>5Y avg {display(s.average,item.yield)}</span><span>Median {display(s.median,item.yield)}</span><span>{s.percentile==null?"N/M":`${(s.percentile*100).toFixed(0)}th pct.`}</span></div></article>})}<article className="valuation-card"><span>Forward P/E</span><strong>N/M</strong><small>No reliable point-in-time consensus source configured; never fabricated.</small></article></section>
    <section className="panel comparison-controls"><div className="comparison-options"><label>Metric<select value={metric} onChange={(event)=>setMetric(event.target.value as ValuationMetric)}>{Object.entries(VALUATION_DEFINITIONS).map(([key,item])=><option key={key} value={key}>{item.label}</option>)}</select></label><label>History<select value={horizon} onChange={(event)=>setHorizon(Number(event.target.value))}><option value="3">3 years</option><option value="5">5 years</option><option value="10">10 years</option><option value="20">20 years</option></select></label><label>Near-average threshold<input type="number" min="0" max="1" step="0.01" value={threshold} onChange={(event)=>setThreshold(Number(event.target.value))}/></label></div></section>
    <section className="panel comparison-chart"><div className="panel-head"><div><span className="panel-kicker">POINT-IN-TIME HISTORY</span><h2>{definition.label}</h2></div><span className="verified">{stats.observations} valid observations · {stats.startDate??"—"} → {stats.endDate??"—"}</span></div><div className="advanced-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chartData}><CartesianGrid stroke="var(--grid)" vertical={false}/><XAxis dataKey="date" tickFormatter={(value)=>String(value).slice(0,7)} tick={{fill:"var(--muted)",fontSize:10}}/><YAxis domain={["auto","auto"]} tickFormatter={(value)=>definition.yield?`${(value*100).toFixed(0)}%`:`${value.toFixed(1)}×`}/><Tooltip formatter={(value)=>display(Number(value),definition.yield)}/><Area dataKey="value" stroke="#4DA3FF" fill="#4DA3FF" fillOpacity={.1} connectNulls={false}/>{stats.average!=null&&<ReferenceLine y={stats.average} stroke="#D8FF5F" strokeDasharray="5 4" label="Average"/>}{stats.median!=null&&<ReferenceLine y={stats.median} stroke="#A78BFA" strokeDasharray="3 4" label="Median"/>}{stats.current!=null&&<ReferenceLine y={stats.current} stroke="#36D399" strokeWidth={2} label="Current"/>}{stats.min!=null&&stats.max!=null&&<Line dataKey={()=>null} stroke="transparent"/>}</ComposedChart></ResponsiveContainer></div><div className="panel-foot"><span>Average {display(stats.average,definition.yield)} · Median {display(stats.median,definition.yield)} · Range {display(stats.min,definition.yield)}–{display(stats.max,definition.yield)}</span><span>{stats.premiumToAverage==null?"N/M":`${(stats.premiumToAverage*100).toFixed(1)}% vs average`} · {stats.percentile==null?"N/M":`${(stats.percentile*100).toFixed(0)}th percentile`}</span></div></section>
    <section className="panel methodology-card"><div><span className="panel-kicker">METHODOLOGY</span><h2>Strict historical availability</h2><p>A TTM snapshot becomes eligible only on its SEC filing date. Negative or zero earnings, EBIT, EBITDA, OCF or FCF denominators produce N/M and are excluded from averages and percentiles.</p></div><div className="formula-box"><code>Market cap = split-adjusted price × diluted shares</code><code>EV = Market cap + Debt − Cash</code><code>5Y premium = Current / 5Y average − 1</code></div></section>
  </div>;
}
