import { derivedValue, valueOf } from "./finance";
import type { AccountingInvariantResult, CompanyDataset, FinancialPeriod } from "./types";

function compare(dataset:CompanyDataset,period:FinancialPeriod,metric:string,invariant:string,observed:number|null,recalculated:number|null,sources:string[],tolerance=.005,classificationTolerance=.03):AccountingInvariantResult{
  const absoluteDifference=observed==null||recalculated==null?null:Math.abs(observed-recalculated);const scale=Math.max(Math.abs(observed??0),Math.abs(recalculated??0),1);const relativeDifference=absoluteDifference==null?null:absoluteDifference/scale;const status=relativeDifference==null?"not-applicable":relativeDifference<=tolerance?"passed":"failed";const severity=status!=="failed"?"info":relativeDifference!<=classificationTolerance?"warning":"error";
  return{id:`${dataset.company.ticker}-${period.periodicity}-${period.periodEnd}-${metric}-${invariant}`,ticker:dataset.company.ticker,metric,period:period.periodEnd,invariant,observed,recalculated,absoluteDifference,relativeDifference,sources:[...new Set(sources.filter(Boolean))],probableCause:status==="not-applicable"?"Required dependency unavailable":status==="passed"?"Within rounding tolerance":severity==="warning"?"Rounding or classification difference":"Unit, sign, period, scope or source-context mismatch",severity,status};
}
const urls=(period:FinancialPeriod,metrics:string[])=>metrics.map((metric)=>period.facts[metric as keyof FinancialPeriod["facts"]]?.provenance.sourceUrl??"");
export function runDatasetInvariants(dataset:CompanyDataset):AccountingInvariantResult[]{const results:AccountingInvariantResult[]=[];for(const period of dataset.periods){const revenue=derivedValue(period,"revenue"),ocf=derivedValue(period,"operatingCashFlow"),capex=derivedValue(period,"capitalExpenditures"),fcf=derivedValue(period,"freeCashFlow"),shares=derivedValue(period,"dilutedShares");results.push(compare(dataset,period,"freeCashFlow","FCF = OCF − normalized Capex",fcf,ocf==null||capex==null?null:ocf-Math.abs(capex),urls(period,["operatingCashFlow","capitalExpenditures"])));
  const grossProfit=derivedValue(period,"grossProfit"),cost=derivedValue(period,"costOfRevenue");results.push(compare(dataset,period,"grossProfit","Gross profit = Revenue − Cost of revenue",grossProfit,revenue==null||cost==null?null:revenue-cost,urls(period,["revenue","costOfRevenue","grossProfit"]),.01,.05));
  for(const [metric,numerator] of [["grossMargin","grossProfit"],["operatingMargin","operatingIncome"],["netMargin","netIncome"],["operatingCashFlowMargin","operatingCashFlow"],["freeCashFlowMargin","freeCashFlow"]])results.push(compare(dataset,period,metric,"Margin = metric / Revenue",derivedValue(period,metric),revenue?derivedValue(period,numerator)!/revenue:null,urls(period,[numerator,"revenue"])));
  for(const [metric,total] of [["revenuePerShare","revenue"],["grossProfitPerShare","grossProfit"],["operatingIncomePerShare","operatingIncome"],["netIncomePerShare","netIncome"],["operatingCashFlowPerShare","operatingCashFlow"],["freeCashFlowPerShare","freeCashFlow"]])results.push(compare(dataset,period,metric,"Per-share = compatible total / diluted shares",derivedValue(period,metric),shares&&period.facts.dilutedShares?.unit==="shares"?derivedValue(period,total)!/shares:null,urls(period,[total,"dilutedShares"])));
  // The one check here that is not self-referential: every other invariant
  // recomputes a formula from the same inputs, so it can only catch plumbing.
  // This compares what we derive against a number the filer published, which
  // is what exposes a wrong income concept or an unadjusted split.
  const reportedEps=valueOf(period,"dilutedEpsReported");
  results.push(compare(dataset,period,"netIncomePerShare","EPS = filer's own reported diluted EPS",derivedValue(period,"netIncomePerShare"),reportedEps,urls(period,["netIncome","dilutedShares","dilutedEpsReported"]),.02,.1));
  results.push(compare(dataset,period,"dilutedShares","Diluted shares ≥ basic shares",shares,valueOf(period,"basicShares")==null?null:Math.max(valueOf(period,"basicShares")!,shares??-Infinity),urls(period,["basicShares","dilutedShares"]),.0001,.01));
  if(period.periodicity==="ttm"&&period.ttmQuarterEnds){const quarters=period.ttmQuarterEnds.map((date)=>dataset.periods.find((item)=>item.periodicity==="quarterly"&&item.periodEnd===date));for(const metric of ["revenue","operatingIncome","netIncome","operatingCashFlow","capitalExpenditures"]){const values=quarters.map((item)=>item?derivedValue(item,metric):null);const recalculated=values.length===4&&values.every((value)=>value!=null)?(values as number[]).reduce((sum,value)=>sum+value,0):null;results.push(compare(dataset,period,metric,"TTM = four consecutive isolated quarters",derivedValue(period,metric),recalculated,urls(period,[metric])));}}
 }
 for(const annual of dataset.periods.filter((period)=>period.periodicity==="annual")){const quarters=dataset.periods.filter((period)=>period.periodicity==="quarterly"&&period.fiscalYear===annual.fiscalYear);for(const metric of ["revenue","operatingIncome","netIncome","operatingCashFlow","capitalExpenditures"]){const values=quarters.map((item)=>derivedValue(item,metric));const recalculated=values.length===4&&values.every((value)=>value!=null)?(values as number[]).reduce((sum,value)=>sum+value,0):null;results.push(compare(dataset,annual,metric,"Annual = Q1 + Q2 + Q3 + Q4",derivedValue(annual,metric),recalculated,urls(annual,[metric]),.01,.05));}}
 return results;}

export interface MarketInvariantInput{ticker:string;date:string;price:number;shares:number;marketCap:number;debt:number|null;cash:number|null;otherAdjustments:number;enterpriseValue:number|null;freeCashFlow:number|null;priceToFreeCashFlow:number|null;freeCashFlowYield:number|null;priceToEarnings:number|null;earningsYield:number|null;priceSource:string;fundamentalSources:string[]}
export function runMarketInvariants(input:MarketInvariantInput){const dataset={company:{ticker:input.ticker}} as CompanyDataset,period={periodEnd:input.date} as FinancialPeriod,sources=[input.priceSource,...input.fundamentalSources];return[
 compare(dataset,period,"marketCapitalization","Market cap = Price × Shares",input.marketCap,input.price*input.shares,sources),
 // An unknown debt or cash balance leaves the identity untestable rather than
 // testable against zero: the old form recomputed EV from `?? 0` inputs and
 // passed every time, which is a check confirming its own mistake.
 compare(dataset,period,"enterpriseValue","EV = Market cap + Debt − Cash + other adjustments",input.enterpriseValue,input.debt==null||input.cash==null?null:input.marketCap+input.debt-input.cash+input.otherAdjustments,sources),
 compare(dataset,period,"priceToFreeCashFlow","P/FCF = Market cap / TTM FCF",input.priceToFreeCashFlow,input.freeCashFlow!=null&&input.freeCashFlow>0?input.marketCap/input.freeCashFlow:null,sources),
 compare(dataset,period,"freeCashFlowYield","FCF yield = TTM FCF / Market cap",input.freeCashFlowYield,input.freeCashFlow!=null&&input.freeCashFlow>0?input.freeCashFlow/input.marketCap:null,sources),
 compare(dataset,period,"earningsYield","Earnings yield = inverse P/E",input.earningsYield,input.priceToEarnings!=null&&input.priceToEarnings>0?1/input.priceToEarnings:null,sources),
 ];}
