import { derivedValue } from "./finance";
import type { DcfAssumptions } from "./dcf";
import type { FinancialPeriod } from "./types";

export type FoundationMetric="revenueGrowth"|"operatingMargin"|"taxRate"|"depreciationPercentRevenue"|"capexPercentRevenue"|"workingCapitalPercentRevenue"|"freeCashFlowMargin"|"shareChange";
export interface FoundationRow {metric:FoundationMetric;label:string;latest:number|null;average3:number|null;average5:number|null;average10:number|null;average20:number|null;suggested:number|null;formula:string}
const mean=(values:Array<number|null>,count:number)=>{const usable=values.slice(-count).filter((value):value is number=>value!=null&&Number.isFinite(value));return usable.length?usable.reduce((sum,value)=>sum+value,0)/usable.length:null};
export function buildDcfFoundation(periods:FinancialPeriod[]):FoundationRow[]{
  const annual=[...periods].filter((period)=>period.periodicity==="annual").sort((a,b)=>a.periodEnd.localeCompare(b.periodEnd));
  const values=(metric:FoundationMetric)=>annual.map((period,index)=>{const revenue=derivedValue(period,"revenue");const prior=annual[index-1];if(metric==="revenueGrowth")return prior&&revenue!=null&&derivedValue(prior,"revenue")!>0?revenue/derivedValue(prior,"revenue")!-1:null;if(metric==="operatingMargin")return derivedValue(period,"operatingMargin");if(metric==="taxRate")return derivedValue(period,"effectiveTaxRate");if(metric==="depreciationPercentRevenue")return revenue!>0?(derivedValue(period,"depreciationAndAmortization")??0)/revenue!:null;if(metric==="capexPercentRevenue")return revenue!>0?Math.abs(derivedValue(period,"capitalExpenditures")??0)/revenue!:null;if(metric==="freeCashFlowMargin")return derivedValue(period,"freeCashFlowMargin");if(metric==="shareChange"){const current=derivedValue(period,"dilutedShares"),before=prior?derivedValue(prior,"dilutedShares"):null;return current!=null&&before!>0?current/before!-1:null}if(!prior||revenue==null||revenue===0)return null;const nwc=derivedValue(period,"netWorkingCapital"),priorNwc=derivedValue(prior,"netWorkingCapital");return nwc==null||priorNwc==null?null:(nwc-priorNwc)/revenue});
  const definitions:Array<[FoundationMetric,string,string]>=[["revenueGrowth","Revenue growth","Revenue / Prior revenue − 1"],["operatingMargin","Operating margin","Operating income / Revenue"],["taxRate","Effective tax rate","Tax expense / Pre-tax income"],["depreciationPercentRevenue","D&A / Revenue","D&A / Revenue"],["capexPercentRevenue","Capex / Revenue","|Capex| / Revenue"],["workingCapitalPercentRevenue","Δ NWC / Revenue","(NWC − Prior NWC) / Revenue"],["freeCashFlowMargin","FCF margin","FCF / Revenue"],["shareChange","Share-count change","Diluted shares / Prior shares − 1"]];
  return definitions.map(([metric,label,formula])=>{const series=values(metric),average3=mean(series,3),average5=mean(series,5),average10=mean(series,10),average20=mean(series,20);return{metric,label,latest:series.at(-1)??null,average3,average5,average10,average20,suggested:average5??average3??series.at(-1)??null,formula}});
}
export function applyDcfFoundation(assumptions:DcfAssumptions,rows:FoundationRow[]){const byMetric=Object.fromEntries(rows.map((row)=>[row.metric,row.suggested]));const repeat=(value:number|null|undefined,fallback:number[])=>value==null?fallback:Array.from({length:assumptions.forecastYears},()=>value);return{...assumptions,revenueGrowth:repeat(byMetric.revenueGrowth,assumptions.revenueGrowth),operatingMargin:repeat(byMetric.operatingMargin,assumptions.operatingMargin),taxRate:repeat(byMetric.taxRate,assumptions.taxRate),depreciationPercentRevenue:repeat(byMetric.depreciationPercentRevenue,assumptions.depreciationPercentRevenue),capexPercentRevenue:repeat(byMetric.capexPercentRevenue,assumptions.capexPercentRevenue),workingCapitalPercentRevenue:repeat(byMetric.workingCapitalPercentRevenue,assumptions.workingCapitalPercentRevenue),directFcfMargin:repeat(byMetric.freeCashFlowMargin,assumptions.directFcfMargin),shareChange:repeat(byMetric.shareChange,assumptions.shareChange)};}
