export type FormulaDataType="reported-flow"|"reported-point"|"calculated-flow"|"margin"|"per-share"|"growth"|"valuation"|"dcf";
export interface FormulaDefinition {
  id:string; label:string; definition:string; formula:string; dataType:FormulaDataType; dependencies:string[];
  signConvention:string; expectedUnit:string; periodicities:string[]; ttmMethod:string; perShareMethod:string;
  nonMeaningfulWhen:string; tests:string[];
}
const all=["Annual","Quarterly","TTM"];
const direct=(id:string,label:string,dataType:FormulaDataType,unit:string,sign="Provider sign retained unless a cash outflow") : FormulaDefinition=>({id,label,definition:`Standardized ${label.toLowerCase()} fact.`,formula:"Direct reported fact",dataType,dependencies:[],signConvention:sign,expectedUnit:unit,periodicities:all,ttmMethod:dataType==="reported-point"?"Latest quarter-end observation":"Sum four consecutive isolated quarters",perShareMethod:"Not applicable",nonMeaningfulWhen:"Missing, incompatible unit/currency or invalid filing context",tests:["periods.test.ts","data-quality.test.ts"]});
const calc=(id:string,label:string,dataType:FormulaDataType,formula:string,dependencies:string[],unit:string,extra:Partial<FormulaDefinition>={}):FormulaDefinition=>({id,label,definition:label,formula,dataType,dependencies,signConvention:"Uses normalized dependency signs",expectedUnit:unit,periodicities:all,ttmMethod:"Calculated from a compatible TTM dependency set",perShareMethod:dataType==="per-share"?"Compatible total / day-weighted diluted shares":"Not applicable",nonMeaningfulWhen:"Any dependency is missing, invalid, zero where used as denominator, or unit/currency incompatible",tests:["finance.test.ts","formula-registry.test.ts"],...extra});

export const FORMULA_REGISTRY:FormulaDefinition[]=[
  direct("revenue","Revenue","reported-flow","currency"),direct("costOfRevenue","Cost of revenue","reported-flow","currency"),direct("grossProfit","Gross profit","reported-flow","currency"),direct("operatingIncome","Operating income / EBIT","reported-flow","currency"),direct("incomeBeforeTax","Pretax income","reported-flow","currency"),direct("netIncome","Net income","reported-flow","currency"),
  calc("netIncomeCommon","Net income attributable to common","calculated-flow","Net income − preferred dividends − noncontrolling attribution",["netIncome","preferredDividends","noncontrollingInterest"],"currency"),
  direct("debtIssued","Debt issued","reported-flow","currency","Positive cash inflow"),direct("debtRepaid","Debt repaid","reported-flow","currency","Positive cash outflow; raw sign retained in audit"),
  direct("operatingCashFlow","Operating cash flow","reported-flow","currency"),direct("capitalExpenditures","Capital expenditures","reported-flow","currency","Positive magnitude for cash outflow; raw sign retained in audit"),direct("acquisitions","Acquisitions","reported-flow","currency","Positive magnitude for cash outflow; raw sign retained in audit"),direct("shareRepurchases","Share repurchases","reported-flow","currency","Positive magnitude for cash outflow; raw sign retained in audit"),direct("shareIssuance","Share issuance","reported-flow","currency","Positive magnitude for cash inflow"),direct("stockBasedCompensation","Stock-based compensation","reported-flow","currency"),direct("dividendsPaid","Dividends paid","reported-flow","currency","Positive magnitude for cash outflow; raw sign retained in audit"),
  calc("freeCashFlow","Free cash flow","calculated-flow","Operating cash flow − normalized capital expenditures",["operatingCashFlow","capitalExpenditures"],"currency"),
  ...[["grossMargin","Gross margin","grossProfit"],["operatingMargin","Operating margin","operatingIncome"],["netMargin","Net margin","netIncome"],["operatingCashFlowMargin","Operating cash flow margin","operatingCashFlow"],["freeCashFlowMargin","Free cash flow margin","freeCashFlow"]].map(([id,label,numerator])=>calc(id,label,"margin",`${label.replace(" margin","")} / Revenue`,[numerator,"revenue"],"percent",{nonMeaningfulWhen:"Revenue is zero, missing or unit/currency incompatible"})),
  ...[["revenuePerShare","Revenue per share","revenue"],["grossProfitPerShare","Gross profit per share","grossProfit"],["operatingIncomePerShare","Operating income per share","operatingIncome"],["netIncomePerShare","Diluted EPS","netIncome"],["operatingCashFlowPerShare","Operating cash flow per share","operatingCashFlow"],["freeCashFlowPerShare","Free cash flow per share","freeCashFlow"]].map(([id,label,total])=>calc(id,label,"per-share",`${label.replace(" per share","")} / diluted weighted-average shares`,[total,"dilutedShares"],"currency/share")),
  calc("basicEps","Basic EPS","per-share","Net income attributable to common / basic weighted-average shares",["netIncomeCommon","basicShares"],"currency/share"),
  direct("basicShares","Basic weighted-average shares","reported-flow","shares"),direct("dilutedShares","Diluted weighted-average shares","reported-flow","shares"),direct("sharesOutstanding","Shares outstanding","reported-point","shares"),
  calc("dilution","Dilution","growth","Current diluted shares / prior diluted shares − 1",["dilutedShares"],"percent"),calc("annualizedDilution","Annualized dilution","growth","(Ending diluted shares / beginning diluted shares)^(1 / actual years) − 1",["dilutedShares"],"percent"),calc("netShareCountReduction","Net share-count reduction","growth","1 − ending diluted shares / beginning diluted shares",["dilutedShares"],"percent"),
  calc("yoy","Year-over-year growth","growth","Current / comparable prior-year period − 1",["selectedMetric"],"percent"),calc("qoq","Quarter-over-quarter growth","growth","Current isolated quarter / previous isolated quarter − 1",["selectedMetric"],"percent"),calc("cagr","CAGR","growth","(Ending / Beginning)^(1 / actual elapsed years) − 1",["selectedMetric"],"percent",{nonMeaningfulWhen:"Endpoints missing, zero, negative, opposite signs, invalid or non-comparable"}),calc("marginPointChange","Margin point change","growth","Ending margin − beginning margin",["selectedMargin"],"percentage points"),
  calc("marketCapitalization","Market capitalization","valuation","Split-adjusted price × period-end shares outstanding (diluted shares only as an explicit fallback)",["stockPrice","sharesOutstanding"],"currency"),calc("enterpriseValue","Enterprise value","valuation","Market capitalization + debt − cash + other claims",["marketCapitalization","totalDebt","cashAndEquivalents"],"currency"),
  ...[["priceToEarnings","P/E","marketCapitalization","netIncome"],["priceToSales","Price / Sales","marketCapitalization","revenue"],["priceToFreeCashFlow","Price / FCF","marketCapitalization","freeCashFlow"],["priceToOperatingCashFlow","Price / OCF","marketCapitalization","operatingCashFlow"],["enterpriseToSales","EV / Sales","enterpriseValue","revenue"],["enterpriseToEbit","EV / EBIT","enterpriseValue","operatingIncome"],["enterpriseToEbitda","EV / EBITDA","enterpriseValue","ebitda"],["enterpriseToFreeCashFlow","EV / FCF","enterpriseValue","freeCashFlow"]].map(([id,label,numerator,denominator])=>calc(id,label,"valuation",`${numerator} / ${denominator}`,[numerator,denominator],"multiple",{nonMeaningfulWhen:"Denominator is zero, negative, missing, invalid or currency-incompatible"})),
  ...[["earningsYield","Earnings yield","netIncome"],["freeCashFlowYield","FCF yield","freeCashFlow"],["buybackYield","Buyback yield","shareRepurchases"],["shareholderYield","Shareholder yield","netShareRepurchases + dividendsPaid"]].map(([id,label,numerator])=>calc(id,label,"valuation",`${numerator} / market capitalization`,[numerator,"marketCapitalization"],"percent")),
  calc("nopat","NOPAT","dcf","EBIT × (1 − normalized tax rate)",["operatingIncome","taxRate"],"currency"),calc("fcff","FCFF","dcf","NOPAT + D&A − Capex − change in working capital",["nopat","depreciationAndAmortization","capitalExpenditures","changeInWorkingCapital"],"currency"),calc("discountFactor","Discount factor","dcf","1 / (1 + WACC)^year",["wacc","year"],"factor"),calc("presentValue","Present value","dcf","Cash flow × discount factor",["fcff","discountFactor"],"currency"),calc("terminalValue","Terminal value","dcf","FCFF(n+1) / (WACC − g), or final FCFF × exit multiple",["fcff","wacc","terminalGrowth"],"currency"),calc("equityValue","Equity value","dcf","Enterprise value + cash − debt − other claims",["enterpriseValue","cashAndEquivalents","totalDebt","otherClaims"],"currency"),calc("intrinsicValuePerShare","Intrinsic value per diluted share","dcf","Equity value / projected ending diluted shares",["equityValue","dilutedShares"],"currency/share"),calc("wacc","WACC","dcf","Equity weight × cost of equity + debt weight × after-tax cost of debt",["marketValueEquity","debtValue","costOfEquity","costOfDebt","taxRate"],"percent"),calc("sensitivity","DCF sensitivity","dcf","Recalculate complete DCF for each WACC / terminal assumption pair",["dcfAssumptions"],"currency/share"),
];

export const FORMULA_BY_ID=Object.fromEntries(FORMULA_REGISTRY.map((item)=>[item.id,item]));
