import { FORMULAS } from "./finance";

export type MetricKind = "currency" | "shares" | "percent" | "perShare" | "ratio";
export interface MetricDefinition { label: string; short: string; color: string; kind: MetricKind; formula?: string }

export const METRICS: Record<string, MetricDefinition> = {
  revenue: { label: "Revenue", short: "Revenue", color: "#53d39c", kind: "currency" },
  grossProfit: { label: "Gross profit", short: "Gross profit", color: "#67b7ff", kind: "currency" },
  costOfRevenue: { label: "Cost of revenue", short: "Cost of revenue", color: "#94a3b8", kind: "currency" },
  operatingIncome: { label: "Operating income", short: "Operating income", color: "#a78bfa", kind: "currency" },
  netIncome: { label: "Net income", short: "Net income", color: "#f4bc56", kind: "currency" },
  operatingCashFlow: { label: "Operating cash flow", short: "Operating CF", color: "#48cbd4", kind: "currency" },
  capitalExpenditures: { label: "Capital expenditures", short: "Capex", color: "#f9737f", kind: "currency" },
  acquisitions: { label: "Acquisitions", short: "Acquisitions", color: "#fb7185", kind: "currency" },
  dividendsPaid: { label: "Dividends paid", short: "Dividends", color: "#f59e0b", kind: "currency" },
  freeCashFlow: { label: "Free cash flow", short: "Free cash flow", color: "#c8f169", kind: "currency", formula: FORMULAS.freeCashFlow },
  grossMargin: { label: "Gross margin", short: "Gross margin", color: "#67b7ff", kind: "percent", formula: FORMULAS.grossMargin },
  operatingMargin: { label: "Operating margin", short: "Operating margin", color: "#a78bfa", kind: "percent", formula: FORMULAS.operatingMargin },
  netMargin: { label: "Net margin", short: "Net margin", color: "#f4bc56", kind: "percent", formula: FORMULAS.netMargin },
  operatingCashFlowMargin: { label: "Operating cash flow margin", short: "OCF margin", color: "#48cbd4", kind: "percent", formula: FORMULAS.operatingCashFlowMargin },
  freeCashFlowMargin: { label: "Free cash flow margin", short: "FCF margin", color: "#c8f169", kind: "percent", formula: FORMULAS.freeCashFlowMargin },
  dilutedShares: { label: "Diluted weighted average shares", short: "Diluted shares", color: "#67b7ff", kind: "shares" },
  basicShares: { label: "Basic weighted average shares", short: "Basic shares", color: "#8c9db7", kind: "shares" },
  sharesOutstanding: { label: "Shares outstanding · period end", short: "Shares outstanding", color: "#f4bc56", kind: "shares" },
  sharesIssued: { label: "Shares issued", short: "Shares issued", color: "#c084fc", kind: "shares" },
  treasuryShares: { label: "Treasury shares", short: "Treasury shares", color: "#fb7185", kind: "shares" },
  stockBasedCompensation: { label: "Stock-based compensation", short: "SBC", color: "#f59e0b", kind: "currency" },
  shareRepurchases: { label: "Gross share repurchases", short: "Buybacks", color: "#53d39c", kind: "currency" },
  shareIssuance: { label: "Stock issuance proceeds", short: "Issuance proceeds", color: "#f9737f", kind: "currency" },
  netShareRepurchases: { label: "Net share repurchases", short: "Net buybacks", color: "#22c55e", kind: "currency", formula: "Gross repurchases − issuance proceeds" },
  revenuePerShare: { label: "Revenue per share", short: "Revenue / share", color: "#53d39c", kind: "perShare", formula: FORMULAS.revenuePerShare },
  grossProfitPerShare: { label: "Gross profit per share", short: "Gross profit / share", color: "#67b7ff", kind: "perShare", formula: FORMULAS.grossProfitPerShare },
  operatingIncomePerShare: { label: "Operating income per share", short: "Operating income / share", color: "#a78bfa", kind: "perShare", formula: FORMULAS.operatingIncomePerShare },
  netIncomePerShare: { label: "EPS · diluted", short: "EPS", color: "#f4bc56", kind: "perShare", formula: FORMULAS.netIncomePerShare },
  operatingCashFlowPerShare: { label: "Operating cash flow per share", short: "OCF / share", color: "#48cbd4", kind: "perShare", formula: FORMULAS.operatingCashFlowPerShare },
  freeCashFlowPerShare: { label: "Free cash flow per share", short: "FCF / share", color: "#c8f169", kind: "perShare", formula: FORMULAS.freeCashFlowPerShare },
  shareCountChange: { label: "Share count change", short: "Share count change", color: "#fb7185", kind: "percent", formula: "Current diluted shares / previous diluted shares − 1" },
  shareCountAbsoluteChange: { label: "Absolute share-count change", short: "Share change", color: "#f43f5e", kind: "shares", formula: "Current diluted shares − previous diluted shares" },
  cumulativeDilution: { label: "Cumulative dilution", short: "Cumulative dilution", color: "#e879f9", kind: "percent", formula: "Current diluted shares / first visible diluted shares − 1" },
  stockBasedCompensationToRevenue: { label: "SBC / Revenue", short: "SBC / Revenue", color: "#f59e0b", kind: "percent", formula: "Stock-based compensation / Revenue" },
  stockBasedCompensationToFcf: { label: "SBC / FCF", short: "SBC / FCF", color: "#f97316", kind: "percent", formula: "Stock-based compensation / Free cash flow" },
  cashConversion: { label: "Cash conversion", short: "FCF / Net income", color: "#2dd4bf", kind: "percent", formula: "Free cash flow / Net income" },
  cashAndEquivalents: { label: "Cash and equivalents", short: "Cash", color: "#32D5E2", kind: "currency" },
  totalDebt: { label: "Total debt", short: "Debt", color: "#FF647C", kind: "currency" },
  currentAssets: { label: "Current assets", short: "Current assets", color: "#4DA3FF", kind: "currency" },
  currentLiabilities: { label: "Current liabilities", short: "Current liabilities", color: "#FF9F43", kind: "currency" },
  incomeBeforeTax: { label: "Income before tax", short: "Pre-tax income", color: "#A78BFA", kind: "currency" },
  incomeTaxExpense: { label: "Income tax expense", short: "Tax expense", color: "#F472B6", kind: "currency" },
  depreciationAndAmortization: { label: "Depreciation & amortization", short: "D&A", color: "#94A3B8", kind: "currency" },
  effectiveTaxRate: { label: "Effective tax rate", short: "Tax rate", color: "#F472B6", kind: "percent", formula: "Income tax expense / Income before tax" },
  netDebt: { label: "Net debt", short: "Net debt", color: "#FF647C", kind: "currency", formula: "Total debt − Cash and equivalents" },
  netWorkingCapital: { label: "Net working capital", short: "NWC", color: "#FF9F43", kind: "currency", formula: "Current assets − Current liabilities − Cash" },
  revenueGrowth: { label: "Revenue growth", short: "Revenue growth", color: "#4DA3FF", kind: "percent", formula: "Current revenue / Previous revenue − 1" },
  freeCashFlowGrowth: { label: "FCF growth", short: "FCF growth", color: "#D8FF5F", kind: "percent", formula: "Current FCF / Previous FCF − 1" },
  freeCashFlowPerShareGrowth: { label: "FCF per share growth", short: "FCF/share growth", color: "#84CC16", kind: "percent", formula: "Current FCF/share / Previous FCF/share − 1" },
  revenueCagr: { label: "Revenue CAGR", short: "Revenue CAGR", color: "#4DA3FF", kind: "percent" },
  freeCashFlowCagr: { label: "FCF CAGR", short: "FCF CAGR", color: "#D8FF5F", kind: "percent" },
  freeCashFlowPerShareCagr: { label: "FCF per share CAGR", short: "FCF/share CAGR", color: "#84CC16", kind: "percent" },
  marketCapitalization: { label: "Market capitalization", short: "Market cap", color: "#36D399", kind: "currency" },
  priceToSales: { label: "Price / Sales", short: "P/S", color: "#4DA3FF", kind: "ratio" },
  priceToEarnings: { label: "Price / Earnings", short: "P/E", color: "#A78BFA", kind: "ratio" },
  priceToFreeCashFlow: { label: "Price / FCF", short: "P/FCF", color: "#D8FF5F", kind: "ratio" },
  freeCashFlowYield: { label: "FCF yield", short: "FCF yield", color: "#36D399", kind: "percent" },
  stockPrice: { label: "Stock price", short: "Stock price", color: "#4DA3FF", kind: "perShare" },
  stockTotalReturn: { label: "Total-return adjusted price", short: "Total return", color: "#D8FF5F", kind: "perShare", formula: "Yahoo adjusted close: stock splits and cash distributions reinvested" },
  marginStability: { label: "Margin stability", short: "Margin stability", color: "#32D5E2", kind: "percent" },
  roic: { label: "Return on invested capital", short: "ROIC", color: "#A78BFA", kind: "percent" },
};

export const VIEW_METRICS = {
  income: ["revenue", "grossProfit", "operatingIncome", "netIncome"],
  cashflow: ["operatingCashFlow", "capitalExpenditures", "freeCashFlow", "acquisitions", "stockBasedCompensation", "shareRepurchases", "shareIssuance", "dividendsPaid", "netShareRepurchases"],
  margins: ["grossMargin", "operatingMargin", "netMargin", "operatingCashFlowMargin", "freeCashFlowMargin", "cashConversion"],
  pershare: ["revenuePerShare", "grossProfitPerShare", "operatingIncomePerShare", "netIncomePerShare", "operatingCashFlowPerShare", "freeCashFlowPerShare"],
  shares: ["dilutedShares", "basicShares", "sharesOutstanding", "sharesIssued", "treasuryShares", "shareCountAbsoluteChange", "shareCountChange", "cumulativeDilution", "shareRepurchases", "stockBasedCompensation", "shareIssuance", "netShareRepurchases", "stockBasedCompensationToRevenue", "stockBasedCompensationToFcf"],
} as const;

export const GROWTH_METRICS = [
  "revenue", "grossProfit", "operatingIncome", "netIncome", "operatingCashFlow", "freeCashFlow",
  "revenuePerShare", "grossProfitPerShare", "operatingIncomePerShare", "netIncomePerShare",
  "operatingCashFlowPerShare", "freeCashFlowPerShare", "basicShares", "dilutedShares", "sharesOutstanding",
];
