/**
 * The S&P MidCap 400, as the index lists it, for keeping more companies ready.
 *
 * Membership taken from the constituents table of Wikipedia's "List of S&P 400
 * companies" on 2026-09-15. Tickers only: the SEC identifier is
 * resolved when a company is built, as it is for any symbol a reader types.
 */
export const MIDCAP_AS_OF = "2026-09-15";

export const MIDCAP: ReadonlyArray<{ ticker: string; name: string }> = [
  { ticker: "AA", name: "Alcoa" },
  { ticker: "AAL", name: "American Airlines Group" },
  { ticker: "AAON", name: "AAON" },
  { ticker: "ACI", name: "Albertsons" },
  { ticker: "ACM", name: "AECOM" },
  { ticker: "ADC", name: "Bloomfield Hills, Michigan" },
  { ticker: "AEIS", name: "Advanced Energy" },
  { ticker: "AFG", name: "American Financial Group" },
  { ticker: "AGCO", name: "AGCO" },
  { ticker: "AHR", name: "Irvine, California" },
  { ticker: "AIT", name: "Applied Industrial Technologies" },
  { ticker: "ALGM", name: "Manchester, New Hampshire" },
  { ticker: "ALK", name: "Alaska Air Group" },
  { ticker: "ALLY", name: "Ally Financial" },
  { ticker: "ALSN", name: "Allison Transmission" },
  { ticker: "ALV", name: "Autoliv" },
  { ticker: "AM", name: "Antero Midstream" },
  { ticker: "AMG", name: "Affiliated Managers Group" },
  { ticker: "AMH", name: "American Homes 4 Rent" },
  { ticker: "AMKR", name: "Amkor Technology" },
  { ticker: "AN", name: "AutoNation" },
  { ticker: "ANF", name: "Abercrombie & Fitch" },
  { ticker: "APG", name: "New Brighton, Minnesota" },
  { ticker: "APPF", name: "AppFolio" },
  { ticker: "AR", name: "Antero Resources" },
  { ticker: "ARMK", name: "Aramark" },
  { ticker: "ARW", name: "Arrow Electronics" },
  { ticker: "ARWR", name: "Arrowhead Pharmaceuticals" },
  { ticker: "ASB", name: "Associated Bank" },
  { ticker: "ASH", name: "Ashland Global" },
  { ticker: "ATI", name: "ATI Inc." },
  { ticker: "ATR", name: "AptarGroup" },
  { ticker: "AVAV", name: "AeroVironment" },
  { ticker: "AVNT", name: "Avient" },
  { ticker: "AVT", name: "Avnet" },
  { ticker: "AVTR", name: "Avantor" },
  { ticker: "AXTA", name: "Axalta" },
  { ticker: "AYI", name: "Acuity Brands" },
  { ticker: "BAH", name: "Booz Allen Hamilton" },
  { ticker: "BBWI", name: "Bath & Body Works, Inc." },
  { ticker: "BC", name: "Brunswick" },
  { ticker: "BCO", name: "Brink's" },
  { ticker: "BDC", name: "Belden Inc." },
  { ticker: "BHF", name: "Brighthouse Financial" },
  { ticker: "BILL", name: "Bill Holdings" },
  { ticker: "BIO", name: "Bio-Rad Laboratories" },
  { ticker: "BJ", name: "BJ's Wholesale Club" },
  { ticker: "BKH", name: "Black Hills Corporation" },
  { ticker: "BMRN", name: "BioMarin Pharmaceutical" },
  { ticker: "BRKR", name: "Bruker" },
  { ticker: "BROS", name: "Dutch Bros Inc." },
  { ticker: "BRX", name: "Brixmor Property Group" },
  { ticker: "BSY", name: "Bentley Systems" },
  { ticker: "BTSG", name: "Louisville, Kentucky" },
  { ticker: "BURL", name: "Burlington Stores" },
  { ticker: "BWA", name: "BorgWarner" },
  { ticker: "BWXT", name: "BWX Technologies" },
  { ticker: "BYD", name: "Boyd Gaming" },
  { ticker: "CACI", name: "CACI International" },
  { ticker: "CAR", name: "Avis Budget Group" },
  { ticker: "CART", name: "Maplebear Inc." },
  { ticker: "CAVA", name: "Cava Group" },
  { ticker: "CBSH", name: "Commerce Bancshares" },
  { ticker: "CBT", name: "Cabot Corp" },
  { ticker: "CCK", name: "Crown Holdings" },
  { ticker: "CDE", name: "Coeur Mining" },
  { ticker: "CDP", name: "COPT Defense Properties" },
  { ticker: "CELH", name: "Celsius Holdings" },
  { ticker: "CFR", name: "Frost Bank" },
  { ticker: "CG", name: "Carlyle Group (The)" },
  { ticker: "CGNX", name: "Cognex" },
  { ticker: "CHDN", name: "Churchill Downs Inc." },
  { ticker: "CHE", name: "Cincinnati" },
  { ticker: "CHH", name: "Choice Hotels" },
  { ticker: "CHRD", name: "Chord Energy" },
  { ticker: "CHWY", name: "Chewy" },
  { ticker: "CLF", name: "Cleveland-Cliffs" },
  { ticker: "CLH", name: "Clean Harbors" },
  { ticker: "CMC", name: "Commercial Metals" },
  { ticker: "CNH", name: "CNH Industrial" },
  { ticker: "CNM", name: "Core & Main" },
  { ticker: "CNO", name: "CNO Financial Group" },
  { ticker: "CNX", name: "CNX Resources" },
  { ticker: "COKE", name: "Coca-Cola Consolidated" },
  { ticker: "COLB", name: "Tacoma, Washington" },
  { ticker: "COLM", name: "Columbia Sportswear" },
  { ticker: "CPRI", name: "Capri Holdings" },
  { ticker: "CR", name: "Crane" },
  { ticker: "CRBG", name: "Corebridge Financial" },
  { ticker: "CROX", name: "Crocs" },
  { ticker: "CRS", name: "Carpenter Technology" },
  { ticker: "CRUS", name: "Cirrus Logic" },
  { ticker: "CSL", name: "Carlisle Companies" },
  { ticker: "CTRE", name: "Dana Point, California" },
  { ticker: "CUBE", name: "CubeSmart" },
  { ticker: "CUZ", name: "Cousins Properties" },
  { ticker: "CVLT", name: "CommVault Systems" },
  { ticker: "CW", name: "Curtiss-Wright" },
  { ticker: "CXT", name: "Crane NXT" },
  { ticker: "CYTK", name: "Cytokinetics" },
  { ticker: "DAR", name: "" },
  { ticker: "DBX", name: "Dropbox" },
  { ticker: "DCI", name: "Donaldson Company" },
  { ticker: "DINO", name: "HF Sinclair" },
  { ticker: "DKS", name: "Dick's Sporting Goods" },
  { ticker: "DLB", name: "Dolby" },
  { ticker: "DOCN", name: "DigitalOcean" },
  { ticker: "DOCS", name: "Doximity" },
  { ticker: "DOCU", name: "Docusign" },
  { ticker: "DT", name: "Dynatrace" },
  { ticker: "DTM", name: "Detroit" },
  { ticker: "DUOL", name: "Duolingo" },
  { ticker: "DY", name: "Palm Beach Gardens, Florida" },
  { ticker: "EEFT", name: "Euronet Worldwide" },
  { ticker: "EGP", name: "" },
  { ticker: "EHC", name: "Encompass Health" },
  { ticker: "ELAN", name: "Elanco" },
  { ticker: "ELF", name: "e.l.f. Beauty" },
  { ticker: "ELS", name: "Chicago" },
  { ticker: "ENS", name: "EnerSys" },
  { ticker: "ENSG", name: "San Juan Capistrano, California" },
  { ticker: "ENTG", name: "Entegris" },
  { ticker: "EPR", name: "EPR Properties" },
  { ticker: "EQH", name: "Equitable Holdings" },
  { ticker: "ESAB", name: "ESAB" },
  { ticker: "ESNT", name: "" },
  { ticker: "EVR", name: "Evercore" },
  { ticker: "EWBC", name: "East West Bancorp" },
  { ticker: "EXEL", name: "Exelixis" },
  { ticker: "EXLS", name: "EXL Service" },
  { ticker: "EXP", name: "Eagle Materials" },
  { ticker: "EXPO", name: "Exponent, Inc." },
  { ticker: "FAF", name: "First American Financial Corporation" },
  { ticker: "FBIN", name: "Fortune Brands Innovations" },
  { ticker: "FCFS", name: "FirstCash" },
  { ticker: "FCN", name: "FTI Consulting" },
  { ticker: "FFIN", name: "Cincinnati" },
  { ticker: "FHI", name: "Federated Hermes" },
  { ticker: "FHN", name: "First Horizon" },
  { ticker: "FIVE", name: "Five Below" },
  { ticker: "FLG", name: "Flagstar Bank" },
  { ticker: "FLR", name: "Fluor" },
  { ticker: "FLS", name: "Flowserve" },
  { ticker: "FN", name: "Santa Clara, California" },
  { ticker: "FNB", name: "FNB Corporation" },
  { ticker: "FND", name: "Floor & Decor" },
  { ticker: "FNF", name: "Fidelity National Financial" },
  { ticker: "FOUR", name: "Shift4" },
  { ticker: "FR", name: "Chicago" },
  { ticker: "FTI", name: "TechnipFMC" },
  { ticker: "G", name: "Genpact" },
  { ticker: "GAP", name: "Gap Inc." },
  { ticker: "GATX", name: "GATX" },
  { ticker: "GBCI", name: "Glacier Bancorp" },
  { ticker: "GEF", name: "Greif, Inc." },
  { ticker: "GGG", name: "Graco Inc." },
  { ticker: "GHC", name: "Graham Holdings" },
  { ticker: "GLPI", name: "Gaming and Leisure Properties" },
  { ticker: "GME", name: "GameStop" },
  { ticker: "GMED", name: "Globus Medical" },
  { ticker: "GNTX", name: "Gentex" },
  { ticker: "GPK", name: "Graphic Packaging" },
  { ticker: "GWRE", name: "Guidewire Software" },
  { ticker: "GXO", name: "GXO Logistics" },
  { ticker: "H", name: "Hyatt" },
  { ticker: "HAE", name: "Haemonetics" },
  { ticker: "HALO", name: "Halozyme" },
  { ticker: "HGV", name: "Hilton Grand Vacations" },
  { ticker: "HIMS", name: "Hims & Hers Health" },
  { ticker: "HL", name: "Hecla Mining" },
  { ticker: "HLI", name: "Houlihan Lokey" },
  { ticker: "HLNE", name: "Hamilton Lane" },
  { ticker: "HOG", name: "Harley-Davidson" },
  { ticker: "HOMB", name: "Home BancShares" },
  { ticker: "HQY", name: "HealthEquity" },
  { ticker: "HR", name: "" },
  { ticker: "HRB", name: "H&R Block" },
  { ticker: "HWC", name: "Hancock Whitney" },
  { ticker: "HXL", name: "Hexcel" },
  { ticker: "IBOC", name: "Intl Bancshares Corp" },
  { ticker: "IDA", name: "Idacorp" },
  { ticker: "IDCC", name: "InterDigital" },
  { ticker: "IESC", name: "IES Holdings" },
  { ticker: "ILMN", name: "Illumina, Inc." },
  { ticker: "INGR", name: "Ingredion" },
  { ticker: "IPGP", name: "IPG Photonics" },
  { ticker: "IRT", name: "" },
  { ticker: "ITT", name: "ITT Inc." },
  { ticker: "JAZZ", name: "Jazz Pharmaceuticals" },
  { ticker: "JEF", name: "Jefferies" },
  { ticker: "JLL", name: "Jones Lang LaSalle" },
  { ticker: "KBH", name: "KB Home" },
  { ticker: "KBR", name: "KBR, Inc." },
  { ticker: "KD", name: "Kyndryl" },
  { ticker: "KEX", name: "Kirby Corporation" },
  { ticker: "KNF", name: "Knife River Corporation" },
  { ticker: "KNSL", name: "" },
  { ticker: "KNX", name: "Knight-Swift" },
  { ticker: "KRC", name: "" },
  { ticker: "KRG", name: "" },
  { ticker: "KRYS", name: "Pittsburgh" },
  { ticker: "KTOS", name: "Kratos Defense & Security Solutions" },
  { ticker: "LAD", name: "Lithia Motors" },
  { ticker: "LAMR", name: "Lamar Advertising Company" },
  { ticker: "LEA", name: "Lear" },
  { ticker: "LECO", name: "Lincoln Electric" },
  { ticker: "LFUS", name: "Littelfuse" },
  { ticker: "LIVN", name: "LivaNova" },
  { ticker: "LNTH", name: "Lantheus Holdings" },
  { ticker: "LOPE", name: "Grand Canyon Education" },
  { ticker: "LPX", name: "Louisiana-Pacific" },
  { ticker: "LSTR", name: "Landstar System" },
  { ticker: "M", name: "Macy's" },
  { ticker: "MANH", name: "Atlanta" },
  { ticker: "MAT", name: "Mattel" },
  { ticker: "MEDP", name: "Medpace" },
  { ticker: "MIDD", name: "Middleby" },
  { ticker: "MKSI", name: "MKS Instruments" },
  { ticker: "MLI", name: "Mueller Industries" },
  { ticker: "MMS", name: "Maximus Inc." },
  { ticker: "MOG.A", name: "Moog Inc." },
  { ticker: "MOH", name: "Molina Healthcare" },
  { ticker: "MORN", name: "Morningstar, Inc." },
  { ticker: "MP", name: "MP Materials" },
  { ticker: "MSA", name: "MSA Safety" },
  { ticker: "MSM", name: "MSC Industrial Direct" },
  { ticker: "MTDR", name: "Dallas" },
  { ticker: "MTG", name: "MGIC Investment Corporation" },
  { ticker: "MTN", name: "Vail Resorts" },
  { ticker: "MTSI", name: "MACOM Technology Solutions" },
  { ticker: "MTZ", name: "MasTec" },
  { ticker: "MUR", name: "Murphy Oil" },
  { ticker: "MUSA", name: "Murphy USA" },
  { ticker: "MZTI", name: "The Marzetti Company" },
  { ticker: "NBIX", name: "Neurocrine Biosciences" },
  { ticker: "NEU", name: "NewMarket Corporation" },
  { ticker: "NFG", name: "National Fuel Gas" },
  { ticker: "NJR", name: "New Jersey Resources" },
  { ticker: "NLY", name: "Annaly Capital Management" },
  { ticker: "NNN", name: "NNN Reit" },
  { ticker: "NOV", name: "NOV Inc." },
  { ticker: "NOVT", name: "" },
  { ticker: "NTNX", name: "Nutanix" },
  { ticker: "NVST", name: "" },
  { ticker: "NVT", name: "nVent Electric" },
  { ticker: "NWE", name: "NorthWestern Energy" },
  { ticker: "NXST", name: "Nexstar Media Group" },
  { ticker: "NXT", name: "Nextpower" },
  { ticker: "NYT", name: "New York Times Company" },
  { ticker: "OC", name: "Owens Corning" },
  { ticker: "OGE", name: "OGE Energy" },
  { ticker: "OGS", name: "One Gas" },
  { ticker: "OHI", name: "" },
  { ticker: "OKTA", name: "Okta, Inc." },
  { ticker: "OLED", name: "Universal Display" },
  { ticker: "OLLI", name: "Ollie's Bargain Outlet" },
  { ticker: "OLN", name: "Olin Corporation" },
  { ticker: "ONB", name: "Old National Bank" },
  { ticker: "ONTO", name: "Onto Innovation" },
  { ticker: "OPCH", name: "" },
  { ticker: "ORA", name: "Ormat Technologies" },
  { ticker: "ORI", name: "Old Republic International" },
  { ticker: "OSK", name: "Oshkosh" },
  { ticker: "OVV", name: "Ovintiv" },
  { ticker: "OZK", name: "Bank OZK" },
  { ticker: "P", name: "Everpure" },
  { ticker: "PAG", name: "Penske Automotive Group" },
  { ticker: "PATH", name: "UiPath" },
  { ticker: "PB", name: "Prosperity Bancshares" },
  { ticker: "PBF", name: "PBF Energy" },
  { ticker: "PCTY", name: "Paylocity" },
  { ticker: "PEGA", name: "Pegasystems" },
  { ticker: "PEN", name: "Penumbra, Inc." },
  { ticker: "PFGC", name: "Performance Food Group" },
  { ticker: "PII", name: "Polaris" },
  { ticker: "PINS", name: "Pinterest" },
  { ticker: "PK", name: "Park Hotels & Resorts" },
  { ticker: "PLNT", name: "Planet Fitness" },
  { ticker: "PNFP", name: "Pinnacle Financial Partners" },
  { ticker: "POR", name: "Portland General Electric" },
  { ticker: "POST", name: "Post Holdings" },
  { ticker: "PPC", name: "Pilgrim's Pride" },
  { ticker: "PR", name: "Midland, Texas" },
  { ticker: "PRI", name: "Primerica" },
  { ticker: "PSN", name: "Parsons Corporation" },
  { ticker: "PVH", name: "PVH Corp." },
  { ticker: "QLYS", name: "Qualys" },
  { ticker: "R", name: "Ryder" },
  { ticker: "RBA", name: "RB Global" },
  { ticker: "RBC", name: "Oxford, Connecticut" },
  { ticker: "REXR", name: "" },
  { ticker: "RGA", name: "Reinsurance Group of America" },
  { ticker: "RGEN", name: "Repligen" },
  { ticker: "RGLD", name: "Royal Gold" },
  { ticker: "RH", name: "RH" },
  { ticker: "RLI", name: "RLI Corp." },
  { ticker: "RMBS", name: "Rambus" },
  { ticker: "RNR", name: "RenaissanceRe" },
  { ticker: "ROIV", name: "Roivant Sciences" },
  { ticker: "ROKU", name: "Roku, Inc." },
  { ticker: "RPM", name: "RPM International" },
  { ticker: "RRC", name: "Range Resources" },
  { ticker: "RRX", name: "Regal Rexnord" },
  { ticker: "RS", name: "Reliance, Inc." },
  { ticker: "RYAN", name: "Chicago" },
  { ticker: "RYN", name: "Rayonier" },
  { ticker: "SAIA", name: "Saia" },
  { ticker: "SAIC", name: "Science Applications Intl Corp" },
  { ticker: "SAM", name: "Boston Beer Company" },
  { ticker: "SANM", name: "Sanmina Corporation" },
  { ticker: "SARO", name: "StandardAero" },
  { ticker: "SBRA", name: "" },
  { ticker: "SCI", name: "Service Corp Intl" },
  { ticker: "SEIC", name: "SEI Investments Company" },
  { ticker: "SF", name: "Stifel" },
  { ticker: "SFM", name: "Sprouts Farmers Market" },
  { ticker: "SGI", name: "Somnigroup International" },
  { ticker: "SHC", name: "Broadview Heights, Ohio" },
  { ticker: "SIGI", name: "" },
  { ticker: "SIRI", name: "SiriusXM" },
  { ticker: "SITM", name: "SiTime" },
  { ticker: "SLAB", name: "Silicon Labs" },
  { ticker: "SLGN", name: "Silgan Holdings" },
  { ticker: "SLM", name: "SLM Corp" },
  { ticker: "SMG", name: "Scotts Miracle-Gro Company" },
  { ticker: "SMTC", name: "Semtech" },
  { ticker: "SN", name: "SharkNinja" },
  { ticker: "SNX", name: "TD Synnex" },
  { ticker: "SOLS", name: "Solstice Advanced Materials" },
  { ticker: "SON", name: "Sonoco" },
  { ticker: "SPXC", name: "SPX Technologies" },
  { ticker: "SR", name: "Spire" },
  { ticker: "SSB", name: "South State Bank" },
  { ticker: "SSD", name: "Simpson Manufacturing" },
  { ticker: "ST", name: "Attleboro, Massachusetts" },
  { ticker: "STAG", name: "Boston" },
  { ticker: "STRL", name: "The Woodlands, Texas" },
  { ticker: "STWD", name: "Greenwich, Connecticut" },
  { ticker: "SUI", name: "Sun Communities" },
  { ticker: "SWX", name: "Southwest Gas Corp" },
  { ticker: "SYNA", name: "Synaptics" },
  { ticker: "TCBI", name: "Texas Capital Bancshares" },
  { ticker: "TEX", name: "Terex" },
  { ticker: "THC", name: "Tenet Health" },
  { ticker: "THG", name: "Hanover Insurance" },
  { ticker: "THO", name: "Thor Industries" },
  { ticker: "TKR", name: "Timken" },
  { ticker: "TLN", name: "Talen Energy" },
  { ticker: "TNL", name: "Travel + Leisure Co." },
  { ticker: "TOL", name: "Toll Brothers" },
  { ticker: "TOST", name: "Toast, Inc." },
  { ticker: "TREX", name: "Trex" },
  { ticker: "TRU", name: "TransUnion" },
  { ticker: "TTC", name: "Toro" },
  { ticker: "TTEK", name: "Tetra Tech" },
  { ticker: "TTMI", name: "TTM Technologies" },
  { ticker: "TWLO", name: "Twilio" },
  { ticker: "TXNM", name: "TXNM Energy" },
  { ticker: "TXRH", name: "Texas Roadhouse" },
  { ticker: "UBSI", name: "United Bankshares" },
  { ticker: "UFPI", name: "UFP Industries" },
  { ticker: "UGI", name: "UGI Corp" },
  { ticker: "ULS", name: "UL Solutions" },
  { ticker: "UMBF", name: "UMB Financial Corp." },
  { ticker: "UNM", name: "Unum" },
  { ticker: "USFD", name: "US Foods" },
  { ticker: "UTHR", name: "United Therapeutics" },
  { ticker: "VAL", name: "Valaris" },
  { ticker: "VC", name: "Visteon" },
  { ticker: "VFC", name: "VF Corporation" },
  { ticker: "VIAV", name: "Viavi Solutions" },
  { ticker: "VICR", name: "Vicor Corporation" },
  { ticker: "VLY", name: "Valley Bank" },
  { ticker: "VMI", name: "Valmont Industries" },
  { ticker: "VNO", name: "Vornado Realty Trust" },
  { ticker: "VNOM", name: "Midland, Texas" },
  { ticker: "VNT", name: "Vontier" },
  { ticker: "VOYA", name: "Voya Financial" },
  { ticker: "VVV", name: "Valvoline" },
  { ticker: "WAL", name: "Western Alliance Bancorporation" },
  { ticker: "WCC", name: "WESCO International" },
  { ticker: "WEX", name: "WEX Inc." },
  { ticker: "WFRD", name: "Weatherford International" },
  { ticker: "WH", name: "Wyndham Hotels & Resorts" },
  { ticker: "WHR", name: "Whirlpool Corporation" },
  { ticker: "WING", name: "Wingstop" },
  { ticker: "WLK", name: "Westlake Corporation" },
  { ticker: "WMG", name: "Warner Music Group" },
  { ticker: "WMS", name: "Advanced Drainage Systems" },
  { ticker: "WPC", name: "W. P. Carey" },
  { ticker: "WSO", name: "Watsco" },
  { ticker: "WTFC", name: "Wintrust Financial" },
  { ticker: "WTRG", name: "Essential Utilities" },
  { ticker: "WTS", name: "Watts Water Technologies" },
  { ticker: "WWD", name: "Woodward, Inc." },
  { ticker: "XPO", name: "XPO, Inc." },
  { ticker: "XRAY", name: "Dentsply Sirona" },
  { ticker: "YETI", name: "Yeti Holdings" },
  { ticker: "ZION", name: "Zions Bancorporation" },
];
